const idiomasDisponibles=["es","en","de","fi","fr","it","ja","zh"];
const idioma=(navigator.languages||[navigator.language]).map(v=>v.toLowerCase().split("-")[0]).find(v=>idiomasDisponibles.includes(v))||"en";
const estructuraFuegos=[
{id:"stone",nombre:"Mantra"},
{id:"maze",nombre:"El Jardín"},
{id:"klotski",nombre:"Mudras"},
{id:"connectfour",nombre:"El Séptimo Sello"},
{id:"hanoi",nombre:"Hanoi"},
{id:"object",nombre:"Op-Art"},
{id:"tower",nombre:"Persia"},
{id:"uri",nombre:"Uri"},
{id:"nine",nombre:"Numero 9"},
{id:"dissolution",nombre:""}
];
const fuegos=estructuraFuegos.map(({id})=>id);
const volver=document.getElementById("back-link"),navegacion=document.getElementById("fire-nav");
let textos={},fuegoActual="stone",entradaFuego=performance.now(),fuegoIniciado=false,quemando=false;
const seccion=n=>document.querySelector(`[data-fire="${n}"]`);
function esTactil(){return matchMedia("(hover:none), (pointer:coarse)").matches}
function estado(n,t=""){const e=document.querySelector(`[data-status="${n}"]`);if(e)e.textContent=t}
function ceniza(origen){const r=origen.getBoundingClientRect(),c=document.createElement("div");c.className="embers";for(let i=0;i<48;i++){const p=document.createElement("i");p.className=i%5?"ember":"smoke";p.style.cssText=`--x:${r.left+Math.random()*r.width}px;--y:${r.top+r.height*(.2+Math.random()*.7)}px;--s:${1+Math.random()*4}px;--dx:${-34+Math.random()*68}px;--rise:${30+Math.random()*110}px;animation-delay:${Math.random()*.38}s`;c.appendChild(p)}document.body.appendChild(c);setTimeout(()=>c.remove(),2400)}
function consumir(nombre,reiniciar,{permanecer=false}={}){if(quemando)return;quemando=true;const f=seccion(nombre);f.classList.add("is-burning");ceniza(f.querySelector(".drawing,.instrument")||f);window.observarUgju?.("fire_complete",nombre);setTimeout(()=>{reiniciar?.();f.classList.remove("is-burning");f.classList.toggle("is-consumed",permanecer);quemando=false},2100)}
function completarNueve(){if(quemando)return;quemando=true;const casa=document.querySelector(".house"),final=puntosObjetivo[7]||puntosObjetivo.at(-1);ceniza({getBoundingClientRect:()=>{const r=contenedorNueve.getBoundingClientRect();return{left:r.left+final.x-14,top:r.top+final.y-14,width:28,height:28}}});window.observarUgju?.("fire_complete","nine");setTimeout(()=>casa.classList.add("is-extinguished"),420);setTimeout(()=>{reiniciarNueve();quemando=false;mostrarFuego("dissolution");casa.classList.add("is-restoring");casa.classList.remove("is-extinguished");requestAnimationFrame(()=>requestAnimationFrame(()=>casa.classList.remove("is-restoring")))},1900)}
function mostrarFuego(nombre){if(quemando)return;if(fuegoIniciado)window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000);if(fuegoActual==="dissolution"&&nombre!=="dissolution")graduarRadio(1);if(nombre!==fuegoActual)seccion(nombre)?.classList.remove("is-consumed");fuegoActual=nombre;entradaFuego=performance.now();fuegoIniciado=true;window.observarUgju?.("fire_open",nombre);document.body.classList.toggle("uri-inverted",nombre==="uri");document.body.classList.toggle("world-dissolving",nombre==="dissolution");document.querySelectorAll(".fire").forEach(f=>{const a=f.dataset.fire===nombre;f.hidden=!a;f.classList.toggle("is-active",a)});navegacion.querySelectorAll("button").forEach(i=>i.setAttribute("aria-current",String(i.dataset.fire===nombre)));history.replaceState(null,"",`#${nombre}`);({nine:prepararNueve,maze:prepararLaberinto,klotski:prepararKlotski,hanoi:dibujarHanoi,uri:prepararUri,dissolution:reiniciarDisolucion}[nombre]||(()=>{}))()}
function moverFuego(d){const i=fuegos.indexOf(fuegoActual),s=i+d;if(s>=0&&s<fuegos.length)mostrarFuego(fuegos[s])}
function crearNavegacion(){estructuraFuegos.forEach(({id,nombre},indice)=>{const b=document.createElement("button");b.type="button";b.dataset.fire=id;b.setAttribute("aria-label",`${indice+1}. ${nombre}`);b.title=`${indice+1}. ${nombre}`;b.onclick=()=>mostrarFuego(id);navegacion.appendChild(b)})}
async function cargarTextos(){let codigo=idioma,r=await fetch(`lang/${codigo}.json?v=20260815-3`);if(!r.ok){codigo="en";r=await fetch("lang/en.json?v=20260815-3")}textos=await r.json();document.documentElement.lang=codigo;document.querySelectorAll("[data-text]").forEach(n=>n.textContent=textos[n.dataset.text]||n.textContent);document.getElementById("nine-instruction").textContent=esTactil()?textos.stay_nine_dots_instruction_touch:textos.stay_nine_dots_instruction_pointer;volver.setAttribute("aria-label",textos.stay_back_to_radio);navegacion.setAttribute("aria-label",textos.stay_fires_label||"Fuegos");crearNavegacion()}

// Nueve puntos
const lienzoNueve=document.getElementById("nine-canvas"),contenedorNueve=document.getElementById("nine-drawing"),ctxNueve=lienzoNueve.getContext("2d");let puntosTrazo=[],dibujando=false,puntosObjetivo=[];
function prepararNueve(){const r=contenedorNueve.getBoundingClientRect(),e=Math.min(devicePixelRatio||1,2);lienzoNueve.width=Math.round(r.width*e);lienzoNueve.height=Math.round(r.height*e);ctxNueve.setTransform(e,0,0,e,0,0);const m=r.width*.27,p=(r.width-m*2)/2;puntosObjetivo=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)puntosObjetivo.push({x:m+x*p,y:m+y*p});dibujarNueve()}
function dibujarNueve(){const r=contenedorNueve.getBoundingClientRect();ctxNueve.clearRect(0,0,r.width,r.height);ctxNueve.fillStyle="#222";puntosObjetivo.forEach(p=>{ctxNueve.beginPath();ctxNueve.arc(p.x,p.y,esTactil()?5.8:4.6,0,Math.PI*2);ctxNueve.fill()});if(puntosTrazo.length<2)return;ctxNueve.strokeStyle="#222";ctxNueve.lineWidth=esTactil()?11:3.2;ctxNueve.lineCap="round";ctxNueve.lineJoin="round";ctxNueve.beginPath();ctxNueve.moveTo(puntosTrazo[0].x,puntosTrazo[0].y);puntosTrazo.slice(1).forEach(p=>ctxNueve.lineTo(p.x,p.y));ctxNueve.stroke()}
function punto(e,el=lienzoNueve){const r=el.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function distanciaSegmento(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=dx||dy?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function simplificar(ps,t){if(ps.length<=2)return ps;let m=0,i=0;for(let n=1;n<ps.length-1;n++){const d=distanciaSegmento(ps[n],ps[0],ps.at(-1));if(d>m){m=d;i=n}}if(m<=t)return[ps[0],ps.at(-1)];return simplificar(ps.slice(0,i+1),t).slice(0,-1).concat(simplificar(ps.slice(i),t))}
function reiniciarNueve(){dibujando=false;puntosTrazo=[];dibujarNueve()}
lienzoNueve.onpointerdown=e=>{if(e.button>0||quemando)return;e.preventDefault();puntosTrazo=[punto(e)];dibujando=true;lienzoNueve.setPointerCapture(e.pointerId)};
lienzoNueve.onpointermove=e=>{if(!dibujando)return;e.preventDefault();const eventos=e.getCoalescedEvents?.()||[e];eventos.forEach(v=>puntosTrazo.push(punto(v)));dibujarNueve()};
lienzoNueve.onpointerup=e=>{if(!dibujando)return;dibujando=false;const ancho=contenedorNueve.clientWidth,crudo=puntosTrazo.slice(),v=simplificar(crudo,ancho*(esTactil()?.026:.02));const segmentosCrudos=crudo.slice(0,-1).map((a,i)=>[a,crudo[i+1]]),tolerancia=ancho*(esTactil()?.09:.068);const toca=puntosObjetivo.every(p=>segmentosCrudos.some(([a,b])=>distanciaSegmento(p,a,b)<=tolerancia));const segmentos=v.length-1,fuera=v.some(p=>p.x<ancho*.2||p.x>ancho*.8||p.y<ancho*.2||p.y>ancho*.8),ok=toca&&fuera&&segmentos>=4&&segmentos<=10;puntosTrazo=v;dibujarNueve();ok?completarNueve():reiniciarNueve()};lienzoNueve.onpointercancel=reiniciarNueve;

// El Jardín: un único sendero continuo, sin cruces ni rutas alternativas.
const laberinto=document.querySelector('[data-firepiece="maze"]'),svgLaberinto=laberinto.querySelector("svg"),corredoresLaberinto=laberinto.querySelector(".maze-corridors"),recorridoLaberinto=laberinto.querySelector(".maze-travelled"),aro=laberinto.querySelector(".maze-ring"),aroTacto=laberinto.querySelector(".maze-ring-hit"),meta=laberinto.querySelector(".maze-goal");
const rutasJardin=[
[[28,270],[28,220],[92,220],[92,268],[150,268],[150,205],[52,205],[52,150],[120,150],[120,92],[42,92],[42,34],[188,34],[188,92],[260,92],[260,158],[190,158],[190,218],[265,218],[265,35]],
[[28,272],[82,272],[82,225],[28,225],[28,178],[110,178],[110,272],[164,272],[164,205],[222,205],[222,270],[272,270],[272,150],[205,150],[205,95],[270,95],[270,30],[150,30],[150,96],[92,96],[92,32],[30,32],[30,144],[152,144],[152,62],[235,62]],
[[25,275],[75,275],[75,232],[25,232],[25,188],[125,188],[125,275],[175,275],[175,225],[225,225],[225,275],[275,275],[275,175],[225,175],[225,125],[275,125],[275,75],[175,75],[175,125],[125,125],[125,75],[75,75],[75,175],[25,175],[25,125],[55,125],[55,25],[225,25],[225,58],[275,58],[275,25]]];
const mapasLaberinto=rutasJardin.map(p=>({p,e:p.slice(1).map((_,i)=>[i,i+1]),s:0,g:p.length-1}));
let nivelLaberinto=0,mapaLaberinto,nodoLaberinto=0,rutaLaberinto=[],arrastrandoAro=false,segmentoLaberinto=0;
const claveArista=(a,b)=>a<b?`${a}-${b}`:`${b}-${a}`;
function vecinosLaberinto(n){return mapaLaberinto.e.filter(e=>e.includes(n)).map(e=>e[0]===n?e[1]:e[0])}
function ponerAro(x,y,traza=[]){[aro,aroTacto].forEach(c=>{c.setAttribute("cx",x);c.setAttribute("cy",y)});recorridoLaberinto.setAttribute("d",traza.length?traza.map((p,k)=>`${k?"L":"M"}${p[0]} ${p[1]}`).join(" "):"")}
function ponerAroNodo(n){const [x,y]=mapaLaberinto.p[n];ponerAro(x,y,mapaLaberinto.p.slice(0,n+1))}
function prepararLaberinto(){mapaLaberinto=mapasLaberinto[nivelLaberinto%mapasLaberinto.length];nodoLaberinto=mapaLaberinto.s;segmentoLaberinto=0;rutaLaberinto=[nodoLaberinto];estado("maze");corredoresLaberinto.replaceChildren();mapaLaberinto.e.forEach(([a,b])=>{const p=mapaLaberinto.p[a],q=mapaLaberinto.p[b],l=document.createElementNS("http://www.w3.org/2000/svg","line");l.setAttribute("x1",p[0]);l.setAttribute("y1",p[1]);l.setAttribute("x2",q[0]);l.setAttribute("y2",q[1]);corredoresLaberinto.appendChild(l)});ponerAroNodo(0);const g=mapaLaberinto.p[mapaLaberinto.g];meta.setAttribute("cx",g[0]);meta.setAttribute("cy",g[1])}
function localSvg(e){const p=svgLaberinto.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svgLaberinto.getScreenCTM().inverse())}
function falloLaberinto(){arrastrandoAro=false;laberinto.classList.remove("is-dragging");navigator.vibrate?.(35);segmentoLaberinto=0;ponerAroNodo(0)}
function proyectarSegmento(p,i){const a=mapaLaberinto.p[i],b=mapaLaberinto.p[i+1],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/(dx*dx+dy*dy)));const x=a[0]+dx*t,y=a[1]+dy*t;return{i,t,x,y,d:Math.hypot(p.x-x,p.y-y)}}
[aro,aroTacto].forEach(n=>n.onpointerdown=e=>{if(quemando)return;arrastrandoAro=true;laberinto.classList.add("is-dragging");svgLaberinto.setPointerCapture(e.pointerId);e.preventDefault()});
function avanzarLaberinto(e){const p=localSvg(e),desde=Math.max(0,segmentoLaberinto-1),hasta=Math.min(mapaLaberinto.p.length-2,segmentoLaberinto+2),candidatos=[];for(let i=desde;i<=hasta;i++)candidatos.push(proyectarSegmento(p,i));const q=candidatos.sort((a,b)=>a.d-b.d)[0];if(q.d>20)return falloLaberinto();if(q.i>segmentoLaberinto+1)return;segmentoLaberinto=q.i+(q.t>.9&&q.i<mapaLaberinto.p.length-2?1:0);const traza=mapaLaberinto.p.slice(0,q.i+1).concat([[q.x,q.y]]);ponerAro(q.x,q.y,traza);if(q.i===mapaLaberinto.p.length-2&&q.t>.9){arrastrandoAro=false;nivelLaberinto++;consumir("maze",prepararLaberinto)}}
svgLaberinto.onpointermove=e=>{if(!arrastrandoAro)return;e.preventDefault();for(const evento of(e.getCoalescedEvents?.()||[e])){avanzarLaberinto(evento);if(!arrastrandoAro)break}};svgLaberinto.onpointerup=()=>{if(arrastrandoAro){arrastrandoAro=false;laberinto.classList.remove("is-dragging")}};svgLaberinto.onpointercancel=falloLaberinto;

// Mudras: la pieza acompaña continuamente al dedo o mouse y se asienta al soltar.
const klotski=document.querySelector('[data-firepiece="klotski"]');let nivelKlotski=0,piezas=[];
const esquemas=[[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[0,2,1,2],[3,2,1,2],[1,2,2,1],[0,4,1,1],[3,4,1,1]],[[1,0,2,2,1],[0,0,1,1],[3,0,1,1],[0,1,1,2],[3,1,1,2],[1,2,1,2],[2,2,1,2],[0,3,1,1],[3,3,1,1]],[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[1,2,2,1],[0,2,1,1],[3,2,1,1],[0,3,2,1],[2,3,2,1]]];
function libre(p,nx,ny){if(nx<0||ny<0||nx+p.w>4||ny+p.h>5)return false;return !piezas.some(o=>o!==p&&nx<o.x+o.w&&nx+p.w>o.x&&ny<o.y+o.h&&ny+p.h>o.y)}
function dibujarKlotski(){klotski.replaceChildren();piezas.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.className=p.key?"is-key":"";b.style.cssText=`--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}`;b.setAttribute("aria-label",p.key?"Pieza principal":`Pieza ${i+1}`);let sx=0,sy=0,dx=0,dy=0;b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;dx=dy=0;b.classList.add("is-dragging");b.setPointerCapture(e.pointerId)};b.onpointermove=e=>{if(!b.hasPointerCapture(e.pointerId))return;dx=e.clientX-sx;dy=e.clientY-sy;const celda=klotski.clientWidth/4,vertical=Math.abs(dy)>Math.abs(dx);if(vertical)dx=0;else dy=0;dx=Math.max(-p.x*celda,Math.min((4-p.x-p.w)*celda,dx));dy=Math.max(-p.y*celda,Math.min((5-p.y-p.h)*celda,dy));b.style.transform=`translate(${dx}px,${dy}px)`};b.onpointerup=e=>{b.classList.remove("is-dragging");const celda=klotski.clientWidth/4,mx=Math.round(dx/celda),my=Math.round(dy/celda),pasos=Math.max(Math.abs(mx),Math.abs(my)),sxPaso=Math.sign(mx),syPaso=Math.sign(my);for(let n=0;n<pasos&&libre(p,p.x+sxPaso,p.y+syPaso);n++){p.x+=sxPaso;p.y+=syPaso}dibujarKlotski();if(p.key&&p.x===1&&p.y+p.h===5){nivelKlotski=(nivelKlotski+1)%esquemas.length;consumir("klotski",prepararKlotski)}};b.onpointercancel=()=>dibujarKlotski();klotski.appendChild(b)})}
function prepararKlotski(){piezas=esquemas[nivelKlotski].map(([x,y,w,h,key])=>({x,y,w,h,key:!!key}));estado("klotski");dibujarKlotski()}

// Persia: cuatro en raya, X contra el círculo de la muerte.
const cuatroEnRaya=document.querySelector('[data-firepiece="connectfour"]'),filasRaya=6,columnasRaya=7;let tableroRaya=Array(filasRaya*columnasRaya).fill(""),finRaya=false;
const indiceRaya=(fila,columna)=>fila*columnasRaya+columna;
function filaLibre(columna){for(let fila=filasRaya-1;fila>=0;fila--)if(!tableroRaya[indiceRaya(fila,columna)])return fila;return-1}
function ganadorRaya(marca){for(let fila=0;fila<filasRaya;fila++)for(let columna=0;columna<columnasRaya;columna++)for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){let n=0;for(;n<4;n++){const f=fila+dr*n,c=columna+dc*n;if(f<0||f>=filasRaya||c<0||c>=columnasRaya||tableroRaya[indiceRaya(f,c)]!==marca)break}if(n===4)return true}return false}
function dibujarRaya(){[...cuatroEnRaya.children].forEach((celda,i)=>{const marca=tableroRaya[i];marca?celda.dataset.mark=marca:delete celda.dataset.mark;celda.setAttribute("aria-label",`Fila ${Math.floor(i/columnasRaya)+1}, columna ${i%columnasRaya+1}${marca?marca==="human"?", X":", círculo":""}`)})}
function reiniciarRaya(){tableroRaya=Array(filasRaya*columnasRaya).fill("");finRaya=false;cuatroEnRaya.classList.remove("is-thinking");dibujarRaya();estado("connectfour")}
function terminarRaya(resultado){finRaya=true;const mensaje=resultado==="human"?(textos.stay_connectfour_human||"Encontraste la línea. La muerte te deja avanzar."):resultado==="machine"?(textos.stay_connectfour_machine||"La muerte cerró la forma."):(textos.stay_connectfour_draw||"Nadie cedió.");estado("connectfour",mensaje);cuatroEnRaya.classList.add(`result-${resultado}`);if(resultado==="human")setTimeout(()=>consumir("connectfour",()=>{cuatroEnRaya.classList.remove("result-human");reiniciarRaya();setTimeout(()=>mostrarFuego("hanoi"),0)}),1100);else setTimeout(()=>{cuatroEnRaya.classList.remove("result-machine","result-draw");reiniciarRaya()},1800)}
function soltarFicha(columna,marca){const fila=filaLibre(columna);if(fila<0)return false;tableroRaya[indiceRaya(fila,columna)]=marca;dibujarRaya();return true}
function probarColumna(columna,marca){const fila=filaLibre(columna);if(fila<0)return false;const i=indiceRaya(fila,columna);tableroRaya[i]=marca;const gana=ganadorRaya(marca);tableroRaya[i]="";return gana}
function turnoMuerte(){if(finRaya)return;const disponibles=[0,1,2,3,4,5,6].filter(c=>filaLibre(c)>=0);let columna=disponibles.find(c=>probarColumna(c,"machine"));if(columna===undefined)columna=disponibles.find(c=>probarColumna(c,"human"));if(columna===undefined){const preferencia=[3,2,4,1,5,0,6].filter(c=>disponibles.includes(c));columna=preferencia[Math.floor(Math.random()*Math.min(3,preferencia.length))]}soltarFicha(columna,"machine");cuatroEnRaya.classList.remove("is-thinking");if(ganadorRaya("machine"))terminarRaya("machine");else if(tableroRaya.every(Boolean))terminarRaya("draw")}
for(let i=0;i<filasRaya*columnasRaya;i++){const celda=document.createElement("button"),columna=i%columnasRaya;celda.type="button";celda.setAttribute("role","gridcell");celda.onclick=()=>{if(finRaya||quemando||cuatroEnRaya.classList.contains("is-thinking")||!soltarFicha(columna,"human"))return;if(ganadorRaya("human"))return terminarRaya("human");if(tableroRaya.every(Boolean))return terminarRaya("draw");cuatroEnRaya.classList.add("is-thinking");setTimeout(turnoMuerte,420)};cuatroEnRaya.appendChild(celda)}

// La Torre: Peg Solitaire inglés. Una selección salta en línea sobre otra pieza.
const torre=document.querySelector('[data-firepiece="tower"]');let tableroTorre=[],seleccionTorre=null;
const existeTorre=(fila,columna)=>(fila>=2&&fila<=4)||(columna>=2&&columna<=4);
const posicionTorre=(fila,columna)=>fila*7+columna;
function movimientosTorre(){const movimientos=[];for(let fila=0;fila<7;fila++)for(let columna=0;columna<7;columna++){const origen=posicionTorre(fila,columna);if(tableroTorre[origen]!==1)continue;for(const[df,dc]of[[0,2],[0,-2],[2,0],[-2,0]]){const destinoFila=fila+df,destinoColumna=columna+dc,medio=posicionTorre(fila+df/2,columna+dc/2),destino=posicionTorre(destinoFila,destinoColumna);if(existeTorre(destinoFila,destinoColumna)&&tableroTorre[medio]===1&&tableroTorre[destino]===0)movimientos.push([origen,medio,destino])}}return movimientos}
function dibujarTorre(){[...torre.children].forEach((celda,i)=>{if(tableroTorre[i]===null)return;celda.dataset.peg=String(tableroTorre[i]);celda.classList.toggle("is-selected",i===seleccionTorre);celda.setAttribute("aria-pressed",String(i===seleccionTorre))})}
function reiniciarTorre(){tableroTorre=Array.from({length:49},(_,i)=>{const fila=Math.floor(i/7),columna=i%7;return existeTorre(fila,columna)?1:null});tableroTorre[posicionTorre(3,3)]=0;seleccionTorre=null;torre.classList.remove("is-stalled");estado("tower");dibujarTorre()}
function jugarTorre(i){if(quemando||tableroTorre[i]===null)return;if(tableroTorre[i]===1){seleccionTorre=seleccionTorre===i?null:i;dibujarTorre();return}if(seleccionTorre===null)return;const movimiento=movimientosTorre().find(m=>m[0]===seleccionTorre&&m[2]===i);if(!movimiento){seleccionTorre=null;navigator.vibrate?.(25);dibujarTorre();return}tableroTorre[movimiento[0]]=0;tableroTorre[movimiento[1]]=0;tableroTorre[movimiento[2]]=1;seleccionTorre=null;dibujarTorre();const piezas=tableroTorre.filter(v=>v===1).length;if(piezas===1&&tableroTorre[posicionTorre(3,3)]===1)consumir("tower",reiniciarTorre);else if(!movimientosTorre().length){estado("tower",textos.stay_tower_blocked||"No quedan movimientos. Vuelve a empezar.");torre.classList.add("is-stalled")}}
for(let i=0;i<49;i++){const fila=Math.floor(i/7),columna=i%7,celda=document.createElement("button");celda.type="button";celda.setAttribute("role","gridcell");celda.setAttribute("aria-label",`Fila ${fila+1}, columna ${columna+1}`);if(!existeTorre(fila,columna)){celda.disabled=true;celda.className="is-void"}else celda.onclick=()=>jugarTorre(i);torre.appendChild(celda)}

// Hanoi aumenta de tres a cinco discos.
const hanoi=document.querySelector('[data-firepiece="hanoi"]'),varillas=[...hanoi.querySelectorAll("button")];let nivelHanoi=0,torres=[],seleccionHanoi=null;
function reiniciarHanoi(){const n=3+nivelHanoi;torres=[Array.from({length:n},(_,i)=>n-i),[],[]];seleccionHanoi=null;estado("hanoi");dibujarHanoi()}
function dibujarHanoi(){if(!torres.length)return reiniciarHanoi();const antes=new Map([...hanoi.querySelectorAll("i[data-disk]")].map(e=>[e.dataset.disk,e.getBoundingClientRect()]));varillas.forEach((v,i)=>{v.replaceChildren();delete v.dataset.selected;torres[i].forEach((d,n)=>{const e=document.createElement("i");e.dataset.disk=String(d);e.style.setProperty("--w",`${25+d*11}%`);e.style.setProperty("--b",`${n*10}%`);v.appendChild(e)})});requestAnimationFrame(()=>hanoi.querySelectorAll("i[data-disk]").forEach(e=>{const a=antes.get(e.dataset.disk);if(!a)return;const b=e.getBoundingClientRect(),dx=a.left-b.left,dy=a.top-b.top;if(Math.abs(dx)+Math.abs(dy)<1)return;const arco=-Math.max(28,Math.min(74,Math.abs(dx)*.24));e.animate([{transform:`translate(${dx}px,${dy}px) rotate(-1.5deg)`},{transform:`translate(${dx*.7}px,${arco}px) rotate(-3deg)`,offset:.32},{transform:`translate(${dx*.28}px,${arco*.72}px) rotate(2deg)`,offset:.68},{transform:"translate(0,0) rotate(0)"}],{duration:680,easing:"cubic-bezier(.22,.74,.2,1)"})}))}
varillas.forEach((v,i)=>v.onclick=()=>{if(quemando)return;if(seleccionHanoi===null){if(!torres[i].length)return;seleccionHanoi=i;v.dataset.selected="true";return}const o=seleccionHanoi,d=torres[o].at(-1),tope=torres[i].at(-1);seleccionHanoi=null;dibujarHanoi();if(i===o)return;if(tope&&tope<d){navigator.vibrate?.(25);return}torres[o].pop();torres[i].push(d);dibujarHanoi();if(torres[2].length===3+nivelHanoi){nivelHanoi=(nivelHanoi+1)%3;consumir("hanoi",reiniciarHanoi)}});

// Mantra: mecánica visual de Infinity Loop. Cada pieza es una recta o un cuarto
// de círculo; al girarlas, todas deben formar un único lazo cerrado.
const campoMantra=document.querySelector('[data-firepiece="stone"]'),svgMantra=campoMantra.querySelector("svg");let nivelMantra=0,girosMantra=[],metasMantra=[],ladoMantra=3;
function azarSemilla(n){let s=n*9301+49297;return()=>((s=s*233280%2147483647)/2147483647)}
function mascaraRotada(m,g){for(let i=0;i<g;i++)m=((m<<1)&15)|(m>>3);return m}
function alternarConexionMantra(a,b,d){const op=(d+2)%4;metasMantra[a]^=1<<d;metasMantra[b]^=1<<op}
function conectarCicloMantra(puntos){const direccion=(a,b)=>b[0]<a[0]?0:b[1]>a[1]?1:b[0]>a[0]?2:3,id=([f,c])=>f*ladoMantra+c;for(let i=0;i<puntos.length;i++){let a=[...puntos[i]];const b=puntos[(i+1)%puntos.length],df=Math.sign(b[0]-a[0]),dc=Math.sign(b[1]-a[1]);while(a[0]!==b[0]||a[1]!==b[1]){const q=[a[0]+df,a[1]+dc];alternarConexionMantra(id(a),id(q),direccion(a,q));a=q}}}
const formasInicialesMantra=[
 {lado:4,ciclos:[[[0,1],[0,2],[1,2],[1,3],[2,3],[3,3],[3,2],[2,2],[2,1],[3,1],[3,0],[2,0],[1,0],[1,1]]]},
 {lado:5,ciclos:[[[0,1],[0,3],[1,3],[1,4],[3,4],[3,3],[4,3],[4,1],[3,1],[3,0],[1,0],[1,1]]]},
 {lado:6,ciclos:[[[0,2],[0,3],[1,3],[1,5],[4,5],[4,3],[5,3],[5,2],[4,2],[4,0],[1,0],[1,2]]]},
 {lado:7,ciclos:[[[0,2],[0,4],[1,4],[1,6],[5,6],[5,4],[6,4],[6,2],[5,2],[5,0],[1,0],[1,2]]]},
 {lado:7,ciclos:[[[0,3],[1,3],[1,5],[2,5],[2,6],[4,6],[4,5],[5,5],[5,3],[6,3],[6,2],[5,2],[5,1],[4,1],[4,0],[2,0],[2,1],[1,1],[1,2],[0,2]]]}
];
function crearTopologiaMantra(){const forma=formasInicialesMantra[nivelMantra%formasInicialesMantra.length];ladoMantra=forma.lado;metasMantra=Array(ladoMantra*ladoMantra).fill(0);forma.ciclos.forEach(conectarCicloMantra)}
function glifoMantra(m,celda){const r=celda*.5;return({
 3:`M0 ${-r} A${r} ${r} 0 0 1 ${r} 0`,
 5:`M0 ${-r} L0 ${r}`,
 6:`M${r} 0 A${r} ${r} 0 0 1 0 ${r}`,
 9:`M${-r} 0 A${r} ${r} 0 0 1 0 ${-r}`,
 10:`M${-r} 0 L${r} 0`,
 12:`M0 ${r} A${r} ${r} 0 0 1 ${-r} 0`
 })[m]||""}
function prepararMantra(){const rnd=azarSemilla((nivelMantra+1)*137);crearTopologiaMantra();const activos=metasMantra.map((m,i)=>m?i:-1).filter(i=>i>=0);do{girosMantra=metasMantra.map(m=>m?Math.floor(rnd()*4):0)}while(mantraResuelto());svgMantra.replaceChildren();const celda=300/ladoMantra;metasMantra.forEach((m,i)=>{if(!m)return;const f=Math.floor(i/ladoMantra),c=i%ladoMantra,g=document.createElementNS("http://www.w3.org/2000/svg","g"),p=document.createElementNS("http://www.w3.org/2000/svg","path"),hit=document.createElementNS("http://www.w3.org/2000/svg","rect");g.classList.add("mantra-tile");g.dataset.index=String(i);g.style.setProperty("--cx",`${(c+.5)*celda}px`);g.style.setProperty("--cy",`${(f+.5)*celda}px`);g.style.setProperty("--pulse",`${activos.indexOf(i)*.055}s`);g.setAttribute("role","button");g.setAttribute("tabindex","0");g.setAttribute("aria-label",`Pieza ${activos.indexOf(i)+1} de ${activos.length}`);p.setAttribute("class","mantra-stroke");p.setAttribute("d",glifoMantra(m,celda));hit.setAttribute("class","mantra-hit");hit.setAttribute("x",-celda/2);hit.setAttribute("y",-celda/2);hit.setAttribute("width",celda);hit.setAttribute("height",celda);g.append(p,hit);g.onclick=()=>girarMantra(i);g.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();girarMantra(i)}};svgMantra.appendChild(g)});dibujarMantra();estado("stone",`#${String(nivelMantra+1).padStart(3,"0")}`)}
function dibujarMantra(){[...svgMantra.querySelectorAll(".mantra-tile")].forEach(g=>{const i=Number(g.dataset.index);g.style.transform=`translate(var(--cx),var(--cy)) rotate(${girosMantra[i]*90}deg)`})}
function mantraResuelto(){const activos=metasMantra.map((m,i)=>m?i:-1).filter(i=>i>=0);if(!activos.length)return false;const adyacencias=new Map(activos.map(i=>[i,[]]));for(const i of activos){const f=Math.floor(i/ladoMantra),c=i%ladoMantra,m=mascaraRotada(metasMantra[i],girosMantra[i]);for(let d=0;d<4;d++){if(!(m&(1<<d)))continue;const nf=f+[-1,0,1,0][d],nc=c+[0,1,0,-1][d];if(nf<0||nf>=ladoMantra||nc<0||nc>=ladoMantra)return false;const ni=nf*ladoMantra+nc,otro=mascaraRotada(metasMantra[ni],girosMantra[ni]);if(!otro||!(otro&(1<<((d+2)%4))))return false;adyacencias.get(i).push(ni)}if(adyacencias.get(i).length!==2)return false}const visitados=new Set(),pendientes=[activos[0]];while(pendientes.length){const i=pendientes.pop();if(visitados.has(i))continue;visitados.add(i);adyacencias.get(i).forEach(ni=>{if(!visitados.has(ni))pendientes.push(ni)})}return visitados.size===activos.length}
function girarMantra(i){if(quemando||campoMantra.classList.contains("is-complete"))return;girosMantra[i]=(girosMantra[i]+1)%4;dibujarMantra();if(mantraResuelto()){campoMantra.classList.add("is-complete");estado("stone",textos.stay_stone_warm||"El mantra continúa.");nivelMantra++;setTimeout(()=>consumir("stone",()=>{campoMantra.classList.remove("is-complete");prepararMantra()}),2800)}}

// Op-Art: prismas concéntricos se alinean en una ilusión de profundidad exacta.
const campoObjeto=document.querySelector('[data-firepiece="object"]'),svgObjeto=campoObjeto.querySelector("svg"),botonPerspectiva=campoObjeto.querySelector(".opart-turn");let nivelObjeto=0,girosObjeto=[0,0,0],metasObjeto=[0,0,0];
function bandaOpArt(r,n=0){let d="";for(let i=0;i<6;i++){const a=(i*60-90)*Math.PI/180,x=150+Math.cos(a)*r,y=150+Math.sin(a)*r;d+=`${i?"L":"M"}${(x+(i%2?n:-n)).toFixed(1)} ${y.toFixed(1)} `}return d+"Z"}
function prepararObjeto(){const rnd=azarSemilla(nivelObjeto+71);girosObjeto=[0,0,0];metasObjeto=girosObjeto.map(()=>1+Math.floor(rnd()*5));svgObjeto.replaceChildren();for(let i=0;i<38;i++){const l=document.createElementNS("http://www.w3.org/2000/svg","path");l.setAttribute("class","op-stripe");l.setAttribute("d",bandaOpArt(12+i*4,(i%2)*4));svgObjeto.appendChild(l)}for(let i=0;i<3;i++){const g=document.createElementNS("http://www.w3.org/2000/svg","g"),p=document.createElementNS("http://www.w3.org/2000/svg","path"),zona=document.createElementNS("http://www.w3.org/2000/svg","path"),marca=document.createElementNS("http://www.w3.org/2000/svg","circle"),radio=52+i*39,angulo=(-90-metasObjeto[i]*60)*Math.PI/180;g.classList.add("op-layer");g.setAttribute("role","button");g.setAttribute("tabindex","0");g.setAttribute("aria-label",`Perspectiva ${i+1}`);p.setAttribute("d",bandaOpArt(radio,8+i*2));zona.setAttribute("class","op-hit");zona.setAttribute("d",p.getAttribute("d"));marca.setAttribute("class","op-mark");marca.setAttribute("cx",150+Math.cos(angulo)*radio);marca.setAttribute("cy",150+Math.sin(angulo)*radio);marca.setAttribute("r",5);g.append(p,zona,marca);g.onclick=()=>girarObjeto(i);g.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();girarObjeto(i)}};svgObjeto.appendChild(g)}const punto=document.createElementNS("http://www.w3.org/2000/svg","circle");punto.setAttribute("class","op-pilgrim");punto.setAttribute("cx",150);punto.setAttribute("cy",150);punto.setAttribute("r",4);svgObjeto.appendChild(punto);dibujarObjeto();estado("object",textos.stay_object_status||"Gira cada prisma hasta llevar su punto al eje vertical.")}
function dibujarObjeto(){[...svgObjeto.querySelectorAll(".op-layer")].forEach((g,i)=>{g.style.transform=`rotate(${girosObjeto[i]*60}deg)`;g.classList.toggle("is-aligned",girosObjeto[i]===metasObjeto[i])});campoObjeto.style.setProperty("--perspective",`${(girosObjeto[0]-girosObjeto[2])*2}deg`)}
function comprobarObjeto(){const faltan=girosObjeto.filter((g,n)=>g!==metasObjeto[n]).length;estado("object",faltan?`${faltan} ${faltan===1?"perspectiva busca":"perspectivas buscan"} el eje.`:"La ilusión se abrió.");if(faltan)return;campoObjeto.classList.add("is-revealed");nivelObjeto++;setTimeout(()=>consumir("object",()=>{campoObjeto.classList.remove("is-revealed");prepararObjeto();setTimeout(()=>mostrarFuego("tower"),0)}),700)}
function girarObjeto(i){if(quemando)return;girosObjeto[i]=(girosObjeto[i]+1)%6;dibujarObjeto();comprobarObjeto()}
botonPerspectiva.onclick=()=>{if(quemando)return;girosObjeto=girosObjeto.map((g,i)=>(g+(i===1?2:1))%6);dibujarObjeto();comprobarObjeto()};

// Uri: cabeza y cola, presencia guardiana que aparece y se desvanece.
const campoUri=document.querySelector('[data-firepiece="uri"]'),gatoUri=campoUri.querySelector(".uri-cat");let esperaUri;
function moverUri(){if(fuegoActual!=="uri")return;const x=18+Math.random()*64,y=20+Math.random()*58,rapido=Math.random()<.2;gatoUri.style.setProperty("--uri-x",`${x}%`);gatoUri.style.setProperty("--uri-y",`${y}%`);gatoUri.style.setProperty("--uri-speed",rapido?".55s":`${2.8+Math.random()*2.2}s`);gatoUri.classList.add("is-vanishing");clearTimeout(esperaUri);esperaUri=setTimeout(()=>{gatoUri.classList.remove("is-vanishing");esperaUri=setTimeout(moverUri,rapido?900:3000+Math.random()*4200)},rapido?300:1100+Math.random()*900)}
function prepararUri(){clearTimeout(esperaUri);gatoUri.classList.remove("is-vanishing","is-petted");moverUri()}
function acariciarUri(e){if(e)e.preventDefault();clearTimeout(esperaUri);gatoUri.classList.remove("is-vanishing");gatoUri.classList.add("is-petted");estado("uri",textos.stay_uri_purr||"Uri ronronea.");navigator.vibrate?.([12,30,12]);esperaUri=setTimeout(()=>{gatoUri.classList.remove("is-petted");estado("uri");moverUri()},1800)}
gatoUri.onpointerdown=acariciarUri;gatoUri.onpointermove=e=>{if(e.buttons||e.pointerType==="touch")acariciarUri(e)};

// Sin nombre: cada toque apaga luz, sonido y acción hasta que sólo queda el regreso.
const campoDisolucion=document.querySelector('[data-firepiece="dissolution"]'),ego=campoDisolucion.querySelector(".ego"),veloDisolucion=campoDisolucion.querySelector(".dissolution-veil"),marcasDisolucion=campoDisolucion.querySelector(".dissolution-marks");let toquesDisolucion=0,terminoDisolucion=false;
function graduarRadio(factor){document.querySelectorAll("audio").forEach(a=>a.volume=Math.max(0,Math.min(1,factor)));if(parent!==window)parent.postMessage({type:"ugju-fire-volume",factor},location.origin)}
function reiniciarDisolucion(){toquesDisolucion=0;terminoDisolucion=false;campoDisolucion.classList.remove("is-black","is-reborn");veloDisolucion.style.opacity=0;marcasDisolucion.replaceChildren();marcasDisolucion.style.removeProperty("--expansion");ego.textContent="";ego.className="ego";document.body.style.setProperty("--dissolve","0");graduarRadio(1)}
function marcarVacio(e){if(quemando||terminoDisolucion)return;e.preventDefault();const r=campoDisolucion.getBoundingClientRect(),marca=document.createElement("i"),tam=Math.max(innerWidth,innerHeight)*(.17+Math.random()*.07);marca.style.cssText=`--x:${e.clientX-r.left}px;--y:${e.clientY-r.top}px;--size:${tam}px;--turn:${Math.random()*180}deg`;marcasDisolucion.appendChild(marca);requestAnimationFrame(()=>marca.classList.add("is-spreading"));toquesDisolucion++;const progreso=Math.min(1,toquesDisolucion/14),expansion=1+progreso*1.15;marcasDisolucion.style.setProperty("--expansion",String(expansion));veloDisolucion.style.opacity=String(Math.min(1,Math.max(0,(progreso-.7)*3.34)));graduarRadio(Math.pow(1-progreso,1.35));document.body.style.setProperty("--dissolve",String(progreso));if(progreso<1)return;terminoDisolucion=true;campoDisolucion.classList.add("is-black");window.observarUgju?.("fire_complete","dissolution");setTimeout(()=>{ego.textContent=textos.stay_dissolution_return||"vuelve a la casa";campoDisolucion.classList.add("is-reborn")},2400)}
campoDisolucion.onpointerdown=marcarVacio;

let inicioSwipe=null;function interactivo(e){return e.closest("[data-firepiece],canvas,button,a")};document.addEventListener("touchstart",e=>{if(e.touches.length!==1||interactivo(e.target))return;const t=e.touches[0];inicioSwipe={x:t.clientX,y:t.clientY}},{passive:true});document.addEventListener("touchend",e=>{if(!inicioSwipe)return;const t=e.changedTouches[0],dx=t.clientX-inicioSwipe.x,dy=t.clientY-inicioSwipe.y;inicioSwipe=null;if(Math.abs(dx)>96&&Math.abs(dx)>Math.abs(dy)*1.4)moverFuego(dx<0?1:-1)},{passive:true});
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight")moverFuego(1);if(e.key==="ArrowLeft")moverFuego(-1)});window.addEventListener("pagehide",()=>window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000));volver.onclick=e=>{if(parent===window)return;e.preventDefault();parent.postMessage({type:"close-stay"},location.origin)};window.addEventListener("resize",()=>{if(fuegoActual==="nine")prepararNueve()});
cargarTextos().catch(()=>{}).finally(()=>{prepararKlotski();reiniciarRaya();reiniciarHanoi();prepararMantra();prepararObjeto();reiniciarTorre();mostrarFuego(fuegos.includes(location.hash.slice(1))?location.hash.slice(1):"stone")});
