const idiomasDisponibles=["es","en","de","fi","fr","it","ja","zh"];
const idioma=(navigator.languages||[navigator.language]).map(v=>v.toLowerCase().split("-")[0]).find(v=>idiomasDisponibles.includes(v))||"en";
const fuegos=["nine","maze","klotski","tictactoe","hanoi","stone","object"];
const claves=Object.fromEntries(fuegos.map(n=>[n,`stay_${n==="nine"?"nine_dots":n}_title`]));
const volver=document.getElementById("back-link"),navegacion=document.getElementById("fire-nav");
let textos={},fuegoActual="nine",entradaFuego=performance.now(),fuegoIniciado=false,quemando=false;
const seccion=n=>document.querySelector(`[data-fire="${n}"]`);
function esTactil(){return matchMedia("(hover:none), (pointer:coarse)").matches}
function estado(n,t=""){const e=document.querySelector(`[data-status="${n}"]`);if(e)e.textContent=t}
function nivel(n,v){estado(n,`${textos.stay_level||"Nivel"} ${v}`)}
function ceniza(origen){const r=origen.getBoundingClientRect(),c=document.createElement("div");c.className="embers";for(let i=0;i<48;i++){const p=document.createElement("i");p.className=i%5?"ember":"smoke";p.style.cssText=`--x:${r.left+Math.random()*r.width}px;--y:${r.top+r.height*(.2+Math.random()*.7)}px;--s:${1+Math.random()*4}px;--dx:${-34+Math.random()*68}px;--rise:${30+Math.random()*110}px;animation-delay:${Math.random()*.38}s`;c.appendChild(p)}document.body.appendChild(c);setTimeout(()=>c.remove(),2400)}
function consumir(nombre,reiniciar,{permanecer=false}={}){if(quemando)return;quemando=true;const f=seccion(nombre);f.classList.add("is-burning");ceniza(f.querySelector(".drawing,.instrument")||f);window.observarUgju?.("fire_complete",nombre);setTimeout(()=>{reiniciar?.();f.classList.remove("is-burning");f.classList.toggle("is-consumed",permanecer);quemando=false},2100)}
function completarNueve(){if(quemando)return;quemando=true;const casa=document.querySelector(".house"),final=puntosObjetivo[7]||puntosObjetivo.at(-1);ceniza({getBoundingClientRect:()=>{const r=contenedorNueve.getBoundingClientRect();return{left:r.left+final.x-14,top:r.top+final.y-14,width:28,height:28}}});window.observarUgju?.("fire_complete","nine");setTimeout(()=>casa.classList.add("is-extinguished"),420);setTimeout(()=>{reiniciarNueve();quemando=false;mostrarFuego("maze");casa.classList.add("is-restoring");casa.classList.remove("is-extinguished");requestAnimationFrame(()=>requestAnimationFrame(()=>casa.classList.remove("is-restoring")))},1900)}
function mostrarFuego(nombre){if(quemando)return;if(fuegoIniciado)window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000);if(nombre!==fuegoActual)seccion(nombre)?.classList.remove("is-consumed");fuegoActual=nombre;entradaFuego=performance.now();fuegoIniciado=true;window.observarUgju?.("fire_open",nombre);document.querySelectorAll(".fire").forEach(f=>{const a=f.dataset.fire===nombre;f.hidden=!a;f.classList.toggle("is-active",a)});navegacion.querySelectorAll("button").forEach(i=>i.setAttribute("aria-current",String(i.dataset.fire===nombre)));history.replaceState(null,"",`#${nombre}`);({nine:prepararNueve,maze:prepararLaberinto,klotski:prepararKlotski,hanoi:dibujarHanoi}[nombre]||(()=>{}))()}
function moverFuego(d){const i=fuegos.indexOf(fuegoActual),s=i+d;if(s>=0&&s<fuegos.length)mostrarFuego(fuegos[s])}
function crearNavegacion(){fuegos.forEach(n=>{const b=document.createElement("button");b.type="button";b.dataset.fire=n;b.setAttribute("aria-label",textos[claves[n]]||n);b.onclick=()=>mostrarFuego(n);navegacion.appendChild(b)})}
async function cargarTextos(){let codigo=idioma,r=await fetch(`lang/${codigo}.json?v=20260815-3`);if(!r.ok){codigo="en";r=await fetch("lang/en.json?v=20260815-3")}textos=await r.json();document.documentElement.lang=codigo;document.querySelectorAll("[data-text]").forEach(n=>n.textContent=textos[n.dataset.text]||n.textContent);document.getElementById("nine-instruction").textContent=esTactil()?textos.stay_nine_dots_instruction_touch:textos.stay_nine_dots_instruction_pointer;volver.setAttribute("aria-label",textos.stay_back_to_radio);navegacion.setAttribute("aria-label",textos.stay_fires_label||"Fuegos");crearNavegacion()}

// Nueve puntos
const lienzoNueve=document.getElementById("nine-canvas"),contenedorNueve=document.getElementById("nine-drawing"),ctxNueve=lienzoNueve.getContext("2d");let puntosTrazo=[],dibujando=false,puntosObjetivo=[];
function prepararNueve(){const r=contenedorNueve.getBoundingClientRect(),e=Math.min(devicePixelRatio||1,2);lienzoNueve.width=Math.round(r.width*e);lienzoNueve.height=Math.round(r.height*e);ctxNueve.setTransform(e,0,0,e,0,0);const m=r.width*.27,p=(r.width-m*2)/2;puntosObjetivo=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)puntosObjetivo.push({x:m+x*p,y:m+y*p});dibujarNueve()}
function dibujarNueve(){const r=contenedorNueve.getBoundingClientRect();ctxNueve.clearRect(0,0,r.width,r.height);ctxNueve.fillStyle="#222";puntosObjetivo.forEach(p=>{ctxNueve.beginPath();ctxNueve.arc(p.x,p.y,esTactil()?5.8:4.6,0,Math.PI*2);ctxNueve.fill()});if(puntosTrazo.length<2)return;ctxNueve.strokeStyle="#222";ctxNueve.lineWidth=esTactil()?11:3.2;ctxNueve.lineCap="round";ctxNueve.lineJoin="round";ctxNueve.beginPath();ctxNueve.moveTo(puntosTrazo[0].x,puntosTrazo[0].y);puntosTrazo.slice(1).forEach(p=>ctxNueve.lineTo(p.x,p.y));ctxNueve.stroke()}
function punto(e,el=lienzoNueve){const r=el.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function distanciaSegmento(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=dx||dy?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function simplificar(ps,t){if(ps.length<=2)return ps;let m=0,i=0;for(let n=1;n<ps.length-1;n++){const d=distanciaSegmento(ps[n],ps[0],ps.at(-1));if(d>m){m=d;i=n}}if(m<=t)return[ps[0],ps.at(-1)];return simplificar(ps.slice(0,i+1),t).slice(0,-1).concat(simplificar(ps.slice(i),t))}
function reiniciarNueve(){dibujando=false;puntosTrazo=[];dibujarNueve()}
lienzoNueve.onpointerdown=e=>{if(e.button>0||quemando)return;e.preventDefault();puntosTrazo=[punto(e)];dibujando=true;lienzoNueve.setPointerCapture(e.pointerId)};
lienzoNueve.onpointermove=e=>{if(!dibujando)return;e.preventDefault();const eventos=e.getCoalescedEvents?.()||[e];eventos.forEach(v=>puntosTrazo.push(punto(v)));dibujarNueve()};
lienzoNueve.onpointerup=e=>{if(!dibujando)return;dibujando=false;const v=simplificar(puntosTrazo,contenedorNueve.clientWidth*.025);while(v.length>5)v.splice(1,1);const ok=v.length===5&&puntosObjetivo.every(p=>v.slice(0,-1).some((a,i)=>distanciaSegmento(p,a,v[i+1])<=contenedorNueve.clientWidth*.052));puntosTrazo=v;dibujarNueve();ok?completarNueve():reiniciarNueve()};lienzoNueve.onpointercancel=reiniciarNueve;

// Laberinto: una red real con bifurcaciones, retornos y callejones.
const laberinto=document.querySelector('[data-firepiece="maze"]'),svgLaberinto=laberinto.querySelector("svg"),corredoresLaberinto=laberinto.querySelector(".maze-corridors"),recorridoLaberinto=laberinto.querySelector(".maze-travelled"),aro=laberinto.querySelector(".maze-ring"),aroTacto=laberinto.querySelector(".maze-ring-hit"),meta=laberinto.querySelector(".maze-goal");
const mapasLaberinto=[
{p:[[30,260],[30,205],[85,205],[85,255],[140,255],[140,195],[85,145],[30,145],[30,85],[90,85],[140,120],[140,60],[205,60],[205,120],[260,120],[260,180],[205,180],[205,240],[260,240],[260,55]],e:[[0,1],[1,2],[2,3],[2,6],[3,4],[4,5],[5,6],[5,16],[6,7],[6,10],[7,8],[8,9],[9,10],[10,11],[10,13],[11,12],[12,13],[12,19],[13,14],[14,15],[15,16],[16,17],[17,18]],s:0,g:19},
{p:[[35,265],[35,215],[90,215],[90,265],[150,265],[150,210],[210,210],[265,210],[265,155],[210,155],[150,155],[90,155],[35,155],[35,95],[90,95],[90,40],[150,40],[150,95],[210,95],[265,95],[265,40],[210,40],[210,265]],e:[[0,1],[1,2],[1,12],[2,3],[2,11],[3,4],[4,5],[5,6],[5,10],[6,7],[6,22],[7,8],[8,9],[9,10],[9,18],[10,11],[11,12],[11,14],[12,13],[13,14],[14,15],[14,17],[15,16],[16,17],[17,18],[18,19],[18,21],[19,20],[20,21]],s:0,g:20},
{p:[[30,270],[30,220],[80,220],[80,270],[130,270],[130,220],[180,220],[180,270],[230,270],[270,270],[270,215],[230,215],[230,165],[270,165],[270,110],[220,110],[220,55],[270,55],[170,55],[170,110],[120,110],[120,55],[70,55],[70,110],[30,110],[30,165],[80,165],[130,165],[180,165]],e:[[0,1],[1,2],[1,25],[2,3],[2,26],[3,4],[4,5],[5,6],[5,27],[6,7],[6,28],[7,8],[8,9],[9,10],[10,11],[11,12],[11,8],[12,13],[12,28],[13,14],[14,15],[15,16],[15,19],[16,17],[16,18],[18,19],[18,21],[19,20],[19,28],[20,21],[20,23],[21,22],[22,23],[23,24],[23,26],[24,25],[25,26],[26,27],[27,28]],s:0,g:17}];
let nivelLaberinto=0,mapaLaberinto,nodoLaberinto=0,rutaLaberinto=[],arrastrandoAro=false;
const claveArista=(a,b)=>a<b?`${a}-${b}`:`${b}-${a}`;
function vecinosLaberinto(n){return mapaLaberinto.e.filter(e=>e.includes(n)).map(e=>e[0]===n?e[1]:e[0])}
function ponerAroNodo(n){const [x,y]=mapaLaberinto.p[n];[aro,aroTacto].forEach(c=>{c.setAttribute("cx",x);c.setAttribute("cy",y)});recorridoLaberinto.setAttribute("d",rutaLaberinto.map((i,k)=>`${k?"L":"M"}${mapaLaberinto.p[i].join(" ")}`).join(" "))}
function prepararLaberinto(){mapaLaberinto=mapasLaberinto[nivelLaberinto%mapasLaberinto.length];nodoLaberinto=mapaLaberinto.s;rutaLaberinto=[nodoLaberinto];corredoresLaberinto.replaceChildren();mapaLaberinto.e.forEach(([a,b])=>{const p=mapaLaberinto.p[a],q=mapaLaberinto.p[b],l=document.createElementNS("http://www.w3.org/2000/svg","line");l.setAttribute("x1",p[0]);l.setAttribute("y1",p[1]);l.setAttribute("x2",q[0]);l.setAttribute("y2",q[1]);l.dataset.edge=claveArista(a,b);corredoresLaberinto.appendChild(l)});ponerAroNodo(nodoLaberinto);const g=mapaLaberinto.p[mapaLaberinto.g];meta.setAttribute("cx",g[0]);meta.setAttribute("cy",g[1]);nivel("maze",nivelLaberinto+1)}
function localSvg(e){const p=svgLaberinto.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svgLaberinto.getScreenCTM().inverse())}
function falloLaberinto(){arrastrandoAro=false;laberinto.classList.remove("is-dragging");navigator.vibrate?.(35);nodoLaberinto=mapaLaberinto.s;rutaLaberinto=[nodoLaberinto];ponerAroNodo(nodoLaberinto)}
[aro,aroTacto].forEach(n=>n.onpointerdown=e=>{if(quemando)return;arrastrandoAro=true;laberinto.classList.add("is-dragging");svgLaberinto.setPointerCapture(e.pointerId);e.preventDefault()});svgLaberinto.onpointermove=e=>{if(!arrastrandoAro)return;const p=localSvg(e),opciones=[nodoLaberinto,...vecinosLaberinto(nodoLaberinto)],candidato=opciones.map(i=>({i,d:Math.hypot(mapaLaberinto.p[i][0]-p.x,mapaLaberinto.p[i][1]-p.y)})).sort((a,b)=>a.d-b.d)[0];if(candidato.i!==nodoLaberinto&&candidato.d<30){nodoLaberinto=candidato.i;rutaLaberinto.push(nodoLaberinto);ponerAroNodo(nodoLaberinto);if(nodoLaberinto===mapaLaberinto.g){arrastrandoAro=false;nivelLaberinto++;consumir("maze",prepararLaberinto)}}else if(candidato.d>48)falloLaberinto();e.preventDefault()};svgLaberinto.onpointerup=()=>{if(arrastrandoAro)falloLaberinto()};

// Klotski: arrastrar una pieza hacia una celda libre.
const klotski=document.querySelector('[data-firepiece="klotski"]');let nivelKlotski=0,piezas=[];
const esquemas=[[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[0,2,1,2],[3,2,1,2],[1,2,2,1],[0,4,1,1],[3,4,1,1]],[[1,0,2,2,1],[0,0,1,1],[3,0,1,1],[0,1,1,2],[3,1,1,2],[1,2,1,2],[2,2,1,2],[0,3,1,1],[3,3,1,1]],[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[1,2,2,1],[0,2,1,1],[3,2,1,1],[0,3,2,1],[2,3,2,1]]];
function libre(p,nx,ny){if(nx<0||ny<0||nx+p.w>4||ny+p.h>5)return false;return !piezas.some(o=>o!==p&&nx<o.x+o.w&&nx+p.w>o.x&&ny<o.y+o.h&&ny+p.h>o.y)}
function dibujarKlotski(){klotski.replaceChildren();piezas.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.className=p.key?"is-key":"";b.style.cssText=`--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}`;b.setAttribute("aria-label",p.key?"Pieza principal":`Pieza ${i+1}`);let sx,sy;b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId)};b.onpointerup=e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;const [mx,my]=Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)];if(libre(p,p.x+mx,p.y+my)){p.x+=mx;p.y+=my;dibujarKlotski();if(p.key&&p.x===1&&p.y+p.h===5){nivelKlotski=(nivelKlotski+1)%esquemas.length;consumir("klotski",prepararKlotski)}}};klotski.appendChild(b)})}
function prepararKlotski(){piezas=esquemas[nivelKlotski].map(([x,y,w,h,key])=>({x,y,w,h,key:!!key}));dibujarKlotski();nivel("klotski",nivelKlotski+1)}

// Ta-te-ti clásico: X contra O.
const tresEnRaya=document.querySelector('[data-firepiece="tictactoe"]');let tableroRaya=Array(9).fill(""),finRaya=false;const lineasRaya=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const ganador=m=>lineasRaya.some(l=>l.every(i=>tableroRaya[i]===m));
function reiniciarRaya(){tableroRaya=Array(9).fill("");finRaya=false;tresEnRaya.classList.remove("is-thinking");[...tresEnRaya.children].forEach(c=>delete c.dataset.mark);estado("tictactoe")}
function terminarRaya(){finRaya=true;consumir("tictactoe",reiniciarRaya)}
function maquina(){if(finRaya)return;const libres=tableroRaya.map((v,i)=>v?null:i).filter(i=>i!==null);let n=libres.find(i=>{tableroRaya[i]="machine";const g=ganador("machine");tableroRaya[i]="";return g});if(n===undefined)n=libres.find(i=>{tableroRaya[i]="human";const g=ganador("human");tableroRaya[i]="";return g});if(n===undefined&&libres.includes(4))n=4;if(n===undefined)n=libres[Math.floor(Math.random()*libres.length)];tableroRaya[n]="machine";tresEnRaya.children[n].dataset.mark="machine";tresEnRaya.classList.remove("is-thinking");if(ganador("machine")||tableroRaya.every(Boolean))terminarRaya()}
for(let i=0;i<9;i++){const c=document.createElement("button");c.type="button";c.setAttribute("role","gridcell");c.setAttribute("aria-label",`Casilla ${i+1}`);c.onclick=()=>{if(finRaya||tableroRaya[i]||quemando)return;tableroRaya[i]="human";c.dataset.mark="human";if(ganador("human")||tableroRaya.every(Boolean))return terminarRaya();tresEnRaya.classList.add("is-thinking");setTimeout(maquina,420)};tresEnRaya.appendChild(c)}

// Hanoi aumenta de tres a cinco discos.
const hanoi=document.querySelector('[data-firepiece="hanoi"]'),varillas=[...hanoi.querySelectorAll("button")];let nivelHanoi=0,torres=[],seleccionHanoi=null;
function reiniciarHanoi(){const n=3+nivelHanoi;torres=[Array.from({length:n},(_,i)=>n-i),[],[]];seleccionHanoi=null;dibujarHanoi();nivel("hanoi",nivelHanoi+1)}
function dibujarHanoi(){if(!torres.length)return reiniciarHanoi();varillas.forEach((v,i)=>{v.replaceChildren();delete v.dataset.selected;torres[i].forEach((d,n)=>{const e=document.createElement("i");e.style.setProperty("--w",`${25+d*11}%`);e.style.setProperty("--b",`${n*10}%`);v.appendChild(e)})})}
varillas.forEach((v,i)=>v.onclick=()=>{if(quemando)return;if(seleccionHanoi===null){if(!torres[i].length)return;seleccionHanoi=i;v.dataset.selected="true";return}const o=seleccionHanoi,d=torres[o].at(-1),tope=torres[i].at(-1);seleccionHanoi=null;dibujarHanoi();if(i===o)return;if(tope&&tope<d){navigator.vibrate?.(25);return}torres[o].pop();torres[i].push(d);dibujarHanoi();if(torres[2].length===3+nivelHanoi){nivelHanoi=(nivelHanoi+1)%3;consumir("hanoi",reiniciarHanoi)}});

// Mantras: loops orgánicos generativos, sin último nivel ni silueta repetida.
const campoMantra=document.querySelector('[data-firepiece="stone"]'),svgMantra=campoMantra.querySelector("svg");let nivelMantra=0,girosMantra=[];
function azarSemilla(n){let s=n*9301+49297;return()=>((s=s*233280%2147483647)/2147483647)}
function prepararMantra(){const rnd=azarSemilla(nivelMantra+17),cantidad=6+(nivelMantra%5),radio=75+(nivelMantra%3)*9;girosMantra=Array.from({length:cantidad},()=>1+Math.floor(rnd()*3));svgMantra.replaceChildren();const nucleo=document.createElementNS("http://www.w3.org/2000/svg","circle");nucleo.setAttribute("class","mantra-core");nucleo.setAttribute("cx",150);nucleo.setAttribute("cy",150);nucleo.setAttribute("r",22+(nivelMantra%4)*3);svgMantra.appendChild(nucleo);for(let i=0;i<cantidad;i++){const a=i*360/cantidad,r1=34+12*rnd(),r2=radio+16*rnd(),ancho=16+13*rnd(),g=document.createElementNS("http://www.w3.org/2000/svg","g"),p=document.createElementNS("http://www.w3.org/2000/svg","path");g.classList.add("mantra-petal");g.style.setProperty("--a",`${a}deg`);g.dataset.i=i;p.setAttribute("d",`M150 ${150-r1} C${150-ancho} ${135-r2*.55},${150-ancho*.8} ${150-r2},150 ${150-r2} C${150+ancho*.8} ${150-r2},${150+ancho} ${135-r2*.55},150 ${150-r1}`);g.appendChild(p);g.onclick=()=>girarMantra(i);svgMantra.appendChild(g)}dibujarMantra();nivel("stone",nivelMantra+1)}
function dibujarMantra(){[...svgMantra.querySelectorAll(".mantra-petal")].forEach((g,i)=>g.style.transform=`rotate(calc(var(--a) + ${girosMantra[i]*90}deg))`)}
function girarMantra(i){if(quemando)return;girosMantra[i]=(girosMantra[i]+1)%4;dibujarMantra();if(girosMantra.every(g=>g===0)){campoMantra.classList.add("is-complete");nivelMantra++;setTimeout(()=>consumir("stone",()=>{campoMantra.classList.remove("is-complete");prepararMantra()}),520)}}

// Op-Art: tres perspectivas independientes forman una arquitectura imposible.
const campoObjeto=document.querySelector('[data-firepiece="object"]'),svgObjeto=campoObjeto.querySelector("svg"),botonPerspectiva=campoObjeto.querySelector(".opart-turn");let nivelObjeto=0,girosObjeto=[0,0,0],metasObjeto=[0,0,0];
function bandaOpArt(r,n){let d="";for(let i=0;i<6;i++){const a=(i*60-90)*Math.PI/180,b=((i+1)*60-90)*Math.PI/180,x=150+Math.cos(a)*r,y=150+Math.sin(a)*r*.58,qx=150+Math.cos(b)*r,qy=150+Math.sin(b)*r*.58;d+=`${i?"L":"M"}${x.toFixed(1)} ${y.toFixed(1)} Q${(x+qx)/2+n*(i%2?1:-1)} ${(y+qy)/2-n},${qx.toFixed(1)} ${qy.toFixed(1)} `}return d+"Z"}
function prepararObjeto(){const rnd=azarSemilla(nivelObjeto+71);girosObjeto=[0,0,0];metasObjeto=girosObjeto.map(()=>1+Math.floor(rnd()*5));svgObjeto.replaceChildren();for(let i=0;i<18;i++){const l=document.createElementNS("http://www.w3.org/2000/svg","path");l.setAttribute("class","op-stripe");l.setAttribute("d",bandaOpArt(32+i*6,(i%3-1)*11));svgObjeto.appendChild(l)}for(let i=0;i<3;i++){const g=document.createElementNS("http://www.w3.org/2000/svg","g"),p=document.createElementNS("http://www.w3.org/2000/svg","path");g.classList.add("op-layer");g.dataset.i=i;p.setAttribute("d",bandaOpArt(62+i*34,18-i*3));g.appendChild(p);g.onclick=()=>girarObjeto(i);svgObjeto.appendChild(g)}const punto=document.createElementNS("http://www.w3.org/2000/svg","circle");punto.setAttribute("class","op-pilgrim");punto.setAttribute("cx",150);punto.setAttribute("cy",150);punto.setAttribute("r",7);svgObjeto.appendChild(punto);dibujarObjeto();nivel("object",nivelObjeto+1)}
function dibujarObjeto(){[...svgObjeto.querySelectorAll(".op-layer")].forEach((g,i)=>g.style.transform=`rotate(${girosObjeto[i]*60}deg)`);campoObjeto.style.setProperty("--perspective",`${(girosObjeto[0]-girosObjeto[2])*2}deg`)}
function comprobarObjeto(){if(!girosObjeto.every((g,n)=>g===metasObjeto[n]))return;campoObjeto.classList.add("is-revealed");nivelObjeto++;setTimeout(()=>consumir("object",()=>{campoObjeto.classList.remove("is-revealed");prepararObjeto()}),700)}
function girarObjeto(i){if(quemando)return;girosObjeto[i]=(girosObjeto[i]+1)%6;dibujarObjeto();comprobarObjeto()}
botonPerspectiva.onclick=()=>{if(quemando)return;girosObjeto=girosObjeto.map((g,i)=>(g+(i===1?2:1))%6);dibujarObjeto();comprobarObjeto()};

let inicioSwipe=null;function interactivo(e){return e.closest("[data-firepiece],canvas,button,a")};document.addEventListener("touchstart",e=>{if(e.touches.length!==1||interactivo(e.target))return;const t=e.touches[0];inicioSwipe={x:t.clientX,y:t.clientY}},{passive:true});document.addEventListener("touchend",e=>{if(!inicioSwipe)return;const t=e.changedTouches[0],dx=t.clientX-inicioSwipe.x,dy=t.clientY-inicioSwipe.y;inicioSwipe=null;if(Math.abs(dx)>96&&Math.abs(dx)>Math.abs(dy)*1.4)moverFuego(dx<0?1:-1)},{passive:true});
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight")moverFuego(1);if(e.key==="ArrowLeft")moverFuego(-1)});window.addEventListener("pagehide",()=>window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000));volver.onclick=e=>{if(parent===window)return;e.preventDefault();parent.postMessage({type:"close-stay"},location.origin)};window.addEventListener("resize",()=>{if(fuegoActual==="nine")prepararNueve()});
cargarTextos().catch(()=>{}).finally(()=>{prepararKlotski();reiniciarHanoi();prepararMantra();prepararObjeto();mostrarFuego(fuegos.includes(location.hash.slice(1))?location.hash.slice(1):"nine")});
