const idiomasDisponibles=["es","en","de","fi","fr","it","ja","zh"];
const idioma=(navigator.languages||[navigator.language]).map(v=>v.toLowerCase().split("-")[0]).find(v=>idiomasDisponibles.includes(v))||"en";
const fuegos=["nine","maze","klotski","tictactoe","hanoi","stone","object"];
const claves=Object.fromEntries(fuegos.map(n=>[n,`stay_${n==="nine"?"nine_dots":n}_title`]));
const volver=document.getElementById("back-link"),navegacion=document.getElementById("fire-nav");
let textos={},fuegoActual="nine",entradaFuego=performance.now(),fuegoIniciado=false,quemando=false;
const seccion=n=>document.querySelector(`[data-fire="${n}"]`);
function esTactil(){return matchMedia("(hover:none), (pointer:coarse)").matches}
function estado(n,t=""){const e=document.querySelector(`[data-status="${n}"]`);if(e)e.textContent=t}
function nivel(n,v){estado(n,`${textos.stay_level||"Nivel"} ${v}`)}
function ceniza(origen){const r=origen.getBoundingClientRect(),c=document.createElement("div");c.className="embers";for(let i=0;i<48;i++){const p=document.createElement("i");p.className=i%5?"ember":"smoke";p.style.cssText=`--x:${r.left+Math.random()*r.width}px;--y:${r.top+r.height*(.2+Math.random()*.7)}px;--s:${1+Math.random()*4}px;--dx:${-34+Math.random()*68}px;--rise:${30+Math.random()*110}px;animation-delay:${Math.random()*.38}s`;c.appendChild(p)}document.body.appendChild(c);setTimeout(()=>c.remove(),2400)}
function consumir(nombre,reiniciar,{permanecer=false,avanzar=false,origen=null}={}){if(quemando)return;quemando=true;const f=seccion(nombre);f.classList.add("is-burning");ceniza(origen||f.querySelector(".drawing,.instrument")||f);window.observarUgju?.("fire_complete",nombre);setTimeout(()=>{reiniciar?.();f.classList.remove("is-burning");f.classList.toggle("is-consumed",permanecer);quemando=false;if(avanzar)moverFuego(1)},2100)}
function mostrarFuego(nombre){if(quemando)return;if(fuegoIniciado)window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000);if(nombre!==fuegoActual)seccion(nombre)?.classList.remove("is-consumed");fuegoActual=nombre;entradaFuego=performance.now();fuegoIniciado=true;window.observarUgju?.("fire_open",nombre);document.querySelectorAll(".fire").forEach(f=>{const a=f.dataset.fire===nombre;f.hidden=!a;f.classList.toggle("is-active",a)});navegacion.querySelectorAll("button").forEach(i=>i.setAttribute("aria-current",String(i.dataset.fire===nombre)));history.replaceState(null,"",`#${nombre}`);({nine:prepararNueve,maze:prepararLaberinto,klotski:prepararKlotski,hanoi:dibujarHanoi}[nombre]||(()=>{}))()}
function moverFuego(d){const i=fuegos.indexOf(fuegoActual),s=i+d;if(s>=0&&s<fuegos.length)mostrarFuego(fuegos[s])}
function crearNavegacion(){fuegos.forEach(n=>{const b=document.createElement("button");b.type="button";b.dataset.fire=n;b.setAttribute("aria-label",textos[claves[n]]||n);b.onclick=()=>mostrarFuego(n);navegacion.appendChild(b)})}
async function cargarTextos(){let codigo=idioma,r=await fetch(`lang/${codigo}.json?v=20260815-2`);if(!r.ok){codigo="en";r=await fetch("lang/en.json?v=20260815-2")}textos=await r.json();document.documentElement.lang=codigo;document.querySelectorAll("[data-text]").forEach(n=>n.textContent=textos[n.dataset.text]||n.textContent);document.getElementById("nine-instruction").textContent=esTactil()?textos.stay_nine_dots_instruction_touch:textos.stay_nine_dots_instruction_pointer;volver.setAttribute("aria-label",textos.stay_back_to_radio);navegacion.setAttribute("aria-label",textos.stay_fires_label||"Fuegos");crearNavegacion()}

// Nueve puntos
const lienzoNueve=document.getElementById("nine-canvas"),contenedorNueve=document.getElementById("nine-drawing"),ctxNueve=lienzoNueve.getContext("2d");let puntosTrazo=[],dibujando=false,puntosObjetivo=[];
function prepararNueve(){const r=contenedorNueve.getBoundingClientRect(),e=Math.min(devicePixelRatio||1,2);lienzoNueve.width=Math.round(r.width*e);lienzoNueve.height=Math.round(r.height*e);ctxNueve.setTransform(e,0,0,e,0,0);const m=r.width*.27,p=(r.width-m*2)/2;puntosObjetivo=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)puntosObjetivo.push({x:m+x*p,y:m+y*p});dibujarNueve()}
function dibujarNueve(){const r=contenedorNueve.getBoundingClientRect();ctxNueve.clearRect(0,0,r.width,r.height);ctxNueve.fillStyle="#222";puntosObjetivo.forEach(p=>{ctxNueve.beginPath();ctxNueve.arc(p.x,p.y,esTactil()?5.8:4.6,0,Math.PI*2);ctxNueve.fill()});if(puntosTrazo.length<2)return;ctxNueve.strokeStyle="#222";ctxNueve.lineWidth=esTactil()?11:3.2;ctxNueve.lineCap="round";ctxNueve.lineJoin="round";ctxNueve.beginPath();ctxNueve.moveTo(puntosTrazo[0].x,puntosTrazo[0].y);puntosTrazo.slice(1).forEach(p=>ctxNueve.lineTo(p.x,p.y));ctxNueve.stroke()}
function punto(e,el=lienzoNueve){const r=el.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function distanciaSegmento(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=dx||dy?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function simplificar(ps,t){if(ps.length<=2)return ps;let m=0,i=0;for(let n=1;n<ps.length-1;n++){const d=distanciaSegmento(ps[n],ps[0],ps.at(-1));if(d>m){m=d;i=n}}if(m<=t)return[ps[0],ps.at(-1)];return simplificar(ps.slice(0,i+1),t).slice(0,-1).concat(simplificar(ps.slice(i),t))}
function reiniciarNueve(){dibujando=false;puntosTrazo=[];dibujarNueve()}
lienzoNueve.onpointerdown=e=>{if(e.button>0||quemando)return;e.preventDefault();puntosTrazo=[punto(e)];dibujando=true;lienzoNueve.setPointerCapture(e.pointerId)};
lienzoNueve.onpointermove=e=>{if(!dibujando)return;e.preventDefault();const eventos=e.getCoalescedEvents?.()||[e];eventos.forEach(v=>puntosTrazo.push(punto(v)));dibujarNueve()};
lienzoNueve.onpointerup=e=>{if(!dibujando)return;dibujando=false;const v=simplificar(puntosTrazo,contenedorNueve.clientWidth*.025);while(v.length>5)v.splice(1,1);const ok=v.length===5&&puntosObjetivo.every(p=>v.slice(0,-1).some((a,i)=>distanciaSegmento(p,a,v[i+1])<=contenedorNueve.clientWidth*.052));if(!ok)return reiniciarNueve();puntosTrazo=[];dibujarNueve();const final=puntosObjetivo[7],marca=document.createElement("i");marca.style.cssText=`position:absolute;left:${final.x}px;top:${final.y}px;width:12px;height:12px;transform:translate(-50%,-50%);border-radius:50%`;contenedorNueve.appendChild(marca);seccion("nine").classList.add("nine-complete");consumir("nine",()=>{marca.remove();seccion("nine").classList.remove("nine-complete");reiniciarNueve()},{avanzar:true,origen:marca})};lienzoNueve.onpointercancel=reiniciarNueve;

// Laberinto: el aro debe permanecer sobre el hilo.
const laberinto=document.querySelector('[data-firepiece="maze"]'),svgLaberinto=laberinto.querySelector("svg"),caminoLaberinto=laberinto.querySelector(".maze-path"),aro=laberinto.querySelector(".maze-ring"),aroTacto=laberinto.querySelector(".maze-ring-hit"),meta=laberinto.querySelector(".maze-goal");
const trazados=["M28 265 C28 196 92 225 88 156 S37 52 111 42 S143 126 194 95 S275 43 270 116 S202 168 237 215 S282 261 266 270","M28 265 C88 296 111 230 61 202 S22 125 80 126 S151 196 164 127 S87 43 164 28 S270 48 235 116 S184 189 253 183 S288 242 266 270","M28 265 C76 302 139 267 91 228 S15 195 48 144 S139 203 137 121 S54 67 126 24 S207 88 177 142 S142 223 218 179 S300 181 247 233 S242 264 266 270","M28 265 C90 307 149 272 103 222 S11 181 61 123 S159 215 169 125 S74 52 154 18 S260 77 211 143 S139 238 235 194 S297 239 266 270"];
let nivelLaberinto=0,largoLaberinto=0,arrastrandoAro=false,avanceAro=0;
function ponerAro(l){const p=caminoLaberinto.getPointAtLength(l);[aro,aroTacto].forEach(n=>{n.setAttribute("cx",p.x);n.setAttribute("cy",p.y)})}
function prepararLaberinto(){caminoLaberinto.setAttribute("d",trazados[nivelLaberinto]);largoLaberinto=caminoLaberinto.getTotalLength();avanceAro=0;ponerAro(0);const p=caminoLaberinto.getPointAtLength(largoLaberinto);meta.setAttribute("cx",p.x);meta.setAttribute("cy",p.y);nivel("maze",nivelLaberinto+1)}
function localSvg(e){const p=svgLaberinto.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svgLaberinto.getScreenCTM().inverse())}
function puntoCamino(e){const p=localSvg(e);let mejor={d:Infinity,l:avanceAro};for(let l=Math.max(0,avanceAro-30);l<=Math.min(largoLaberinto,avanceAro+64);l+=2){const q=caminoLaberinto.getPointAtLength(l),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<mejor.d)mejor={d,l}}return mejor}
function falloLaberinto(){arrastrandoAro=false;laberinto.classList.remove("is-dragging");navigator.vibrate?.(35);avanceAro=0;ponerAro(0)}
[aro,aroTacto].forEach(n=>n.onpointerdown=e=>{if(quemando)return;arrastrandoAro=true;laberinto.classList.add("is-dragging");svgLaberinto.setPointerCapture(e.pointerId);e.preventDefault()});svgLaberinto.onpointermove=e=>{if(!arrastrandoAro)return;const p=puntoCamino(e);if(p.d>30||p.l+22<avanceAro){falloLaberinto();return}avanceAro=Math.max(avanceAro,p.l);ponerAro(avanceAro);if(avanceAro>largoLaberinto-15){arrastrandoAro=false;nivelLaberinto=(nivelLaberinto+1)%trazados.length;consumir("maze",prepararLaberinto)}e.preventDefault()};svgLaberinto.onpointerup=()=>{if(arrastrandoAro)falloLaberinto()};

// Klotski: arrastrar una pieza hacia una celda libre.
const klotski=document.querySelector('[data-firepiece="klotski"]');let nivelKlotski=0,piezas=[];
const esquemas=[[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[0,2,1,2],[3,2,1,2],[1,2,2,1],[0,4,1,1],[3,4,1,1]],[[1,0,2,2,1],[0,0,1,1],[3,0,1,1],[0,1,1,2],[3,1,1,2],[1,2,1,2],[2,2,1,2],[0,3,1,1],[3,3,1,1]],[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[1,2,2,1],[0,2,1,1],[3,2,1,1],[0,3,2,1],[2,3,2,1]]];
function libre(p,nx,ny){if(nx<0||ny<0||nx+p.w>4||ny+p.h>5)return false;return !piezas.some(o=>o!==p&&nx<o.x+o.w&&nx+p.w>o.x&&ny<o.y+o.h&&ny+p.h>o.y)}
function dibujarKlotski(){klotski.replaceChildren();piezas.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.className=p.key?"is-key":"";b.style.cssText=`--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}`;b.setAttribute("aria-label",p.key?"Pieza principal":`Pieza ${i+1}`);let sx,sy;b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId)};b.onpointerup=e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;const [mx,my]=Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)];if(libre(p,p.x+mx,p.y+my)){p.x+=mx;p.y+=my;dibujarKlotski();if(p.key&&p.x===1&&p.y+p.h===5){nivelKlotski=(nivelKlotski+1)%esquemas.length;consumir("klotski",prepararKlotski)}}};klotski.appendChild(b)})}
function prepararKlotski(){piezas=esquemas[nivelKlotski].map(([x,y,w,h,key])=>({x,y,w,h,key:!!key}));dibujarKlotski();nivel("klotski",nivelKlotski+1)}

// Ta-te-ti clásico: X contra O.
const tresEnRaya=document.querySelector('[data-firepiece="tictactoe"]');let tableroRaya=Array(9).fill(""),finRaya=false;const lineasRaya=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const ganador=m=>lineasRaya.some(l=>l.every(i=>tableroRaya[i]===m));
function reiniciarRaya(){tableroRaya=Array(9).fill("");finRaya=false;tresEnRaya.classList.remove("is-thinking");[...tresEnRaya.children].forEach(c=>delete c.dataset.mark);estado("tictactoe")}
function terminarRaya(){finRaya=true;consumir("tictactoe",reiniciarRaya)}
function maquina(){if(finRaya)return;const libres=tableroRaya.map((v,i)=>v?null:i).filter(i=>i!==null);let n=libres.find(i=>{tableroRaya[i]="machine";const g=ganador("machine");tableroRaya[i]="";return g});if(n===undefined)n=libres.find(i=>{tableroRaya[i]="human";const g=ganador("human");tableroRaya[i]="";return g});if(n===undefined&&libres.includes(4))n=4;if(n===undefined)n=libres[Math.floor(Math.random()*libres.length)];tableroRaya[n]="machine";tresEnRaya.children[n].dataset.mark="machine";tresEnRaya.classList.remove("is-thinking");if(ganador("machine")||tableroRaya.every(Boolean))terminarRaya()}
for(let i=0;i<9;i++){const c=document.createElement("button");c.type="button";c.setAttribute("role","gridcell");c.setAttribute("aria-label",`Casilla ${i+1}`);c.onclick=()=>{if(finRaya||tableroRaya[i]||quemando)return;tableroRaya[i]="human";c.dataset.mark="human";if(ganador("human")||tableroRaya.every(Boolean))return terminarRaya();tresEnRaya.classList.add("is-thinking");setTimeout(maquina,420)};tresEnRaya.appendChild(c)}

// Hanoi aumenta de tres a cinco discos.
const hanoi=document.querySelector('[data-firepiece="hanoi"]'),varillas=[...hanoi.querySelectorAll("button")];let nivelHanoi=0,torres=[],seleccionHanoi=null;
function reiniciarHanoi(){const n=3+nivelHanoi;torres=[Array.from({length:n},(_,i)=>n-i),[],[]];seleccionHanoi=null;dibujarHanoi();nivel("hanoi",nivelHanoi+1)}
function dibujarHanoi(){if(!torres.length)return reiniciarHanoi();varillas.forEach((v,i)=>{v.replaceChildren();delete v.dataset.selected;torres[i].forEach((d,n)=>{const e=document.createElement("i");e.style.setProperty("--w",`${25+d*11}%`);e.style.setProperty("--b",`${n*10}%`);v.appendChild(e)})})}
varillas.forEach((v,i)=>v.onclick=()=>{if(quemando)return;if(seleccionHanoi===null){if(!torres[i].length)return;seleccionHanoi=i;v.dataset.selected="true";return}const o=seleccionHanoi,d=torres[o].at(-1),tope=torres[i].at(-1);seleccionHanoi=null;dibujarHanoi();if(i===o)return;if(tope&&tope<d){navigator.vibrate?.(25);return}torres[o].pop();torres[i].push(d);dibujarHanoi();if(torres[2].length===3+nivelHanoi){nivelHanoi=(nivelHanoi+1)%3;consumir("hanoi",reiniciarHanoi)}});

// Loop silencioso: cada pieza gira hasta cerrar un único circuito.
const circuito=document.querySelector('[data-firepiece="stone"]');
const conexionesLoop=[[1,2],[1,3],[1,3],[2,3],[0,2],[1,2],[2,3],[0,2],[0,2],[0,1],[0,3],[0,2],[0,1],[1,3],[1,3],[0,3]];
let girosLoop=[];
function ladosLoop(i){return conexionesLoop[i].map(l=>(l+girosLoop[i])%4)}
function loopCompleto(){for(let i=0;i<16;i++){const x=i%4,y=Math.floor(i/4);for(const lado of ladosLoop(i)){const j=lado===0?i-4:lado===1?i+1:lado===2?i+4:i-1;if(j<0||j>15||(lado===1&&x===3)||(lado===3&&x===0)||!ladosLoop(j).includes((lado+2)%4))return false}if((y===0&&ladosLoop(i).includes(0))||(y===3&&ladosLoop(i).includes(2)))return false}return true}
function dibujarLoop(){circuito.replaceChildren();conexionesLoop.forEach((lados,i)=>{const b=document.createElement("button");b.type="button";b.className="loop-tile";b.setAttribute("role","gridcell");b.setAttribute("aria-label",`${textos.stay_loop_piece||"Pieza"} ${i+1}`);b.style.setProperty("--rotation",girosLoop[i]);const rutas=lados.map(l=>l===0?"M50 50V0":l===1?"M50 50H100":l===2?"M50 50V100":"M50 50H0").map(d=>`<path d="${d}"/>`).join("");b.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true">${rutas}<circle cx="50" cy="50" r="5"/></svg>`;b.onclick=()=>{if(quemando)return;girosLoop[i]=(girosLoop[i]+1)%4;b.style.setProperty("--rotation",girosLoop[i]);if(loopCompleto()){circuito.classList.add("is-complete");setTimeout(()=>consumir("stone",prepararLoop),650)}};circuito.appendChild(b)})}
function prepararLoop(){circuito.classList.remove("is-complete");girosLoop=conexionesLoop.map((_,i)=>(i*3+1)%4);dibujarLoop()}

// El giro revela una puerta que estaba dentro de la forma imposible.
const campoObjeto=document.querySelector('[data-firepiece="object"]'),puenteObjeto=campoObjeto.querySelector(".world-bridge"),peregrinoObjeto=campoObjeto.querySelector(".world-pilgrim"),botonGiro=campoObjeto.querySelector(".world-turn"),botonAndar=campoObjeto.querySelector(".world-walk");let giroObjeto=0,pasoObjeto=0;
const destinosObjeto=[{g:1,x:122,y:174},{g:3,x:177,y:142},{g:0,x:226,y:111}];
function dibujarObjeto(){campoObjeto.dataset.turn=giroObjeto;campoObjeto.dataset.step=pasoObjeto;puenteObjeto.style.transform=`rotate(${giroObjeto*60}deg)`}
function reiniciarObjeto(){giroObjeto=0;pasoObjeto=0;campoObjeto.classList.remove("is-crossing");dibujarObjeto();peregrinoObjeto.setAttribute("cx",59);peregrinoObjeto.setAttribute("cy",207)}
botonGiro.onclick=()=>{if(quemando)return;giroObjeto=(giroObjeto+1)%4;dibujarObjeto()};
botonAndar.onclick=()=>{if(quemando||giroObjeto!==destinosObjeto[pasoObjeto].g){navigator.vibrate?.(22);campoObjeto.classList.remove("is-refusing");void campoObjeto.offsetWidth;campoObjeto.classList.add("is-refusing");return}const d=destinosObjeto[pasoObjeto++];campoObjeto.classList.add("is-crossing");peregrinoObjeto.setAttribute("cx",d.x);peregrinoObjeto.setAttribute("cy",d.y);if(pasoObjeto===destinosObjeto.length)setTimeout(()=>consumir("object",reiniciarObjeto),700)};

let inicioSwipe=null;function interactivo(e){return e.closest("[data-firepiece],canvas,button,a")};document.addEventListener("touchstart",e=>{if(e.touches.length!==1||interactivo(e.target))return;const t=e.touches[0];inicioSwipe={x:t.clientX,y:t.clientY}},{passive:true});document.addEventListener("touchend",e=>{if(!inicioSwipe)return;const t=e.changedTouches[0],dx=t.clientX-inicioSwipe.x,dy=t.clientY-inicioSwipe.y;inicioSwipe=null;if(Math.abs(dx)>96&&Math.abs(dx)>Math.abs(dy)*1.4)moverFuego(dx<0?1:-1)},{passive:true});
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight")moverFuego(1);if(e.key==="ArrowLeft")moverFuego(-1)});window.addEventListener("pagehide",()=>window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000));volver.onclick=e=>{if(parent===window)return;e.preventDefault();parent.postMessage({type:"close-stay"},location.origin)};window.addEventListener("resize",()=>{if(fuegoActual==="nine")prepararNueve()});
cargarTextos().catch(()=>{}).finally(()=>{prepararKlotski();reiniciarHanoi();prepararLoop();mostrarFuego(fuegos.includes(location.hash.slice(1))?location.hash.slice(1):"nine")});
