const idiomasDisponibles=["es","en","de","fi","fr","it","ja","zh"];
const idioma=(navigator.languages||[navigator.language]).map(v=>v.toLowerCase().split("-")[0]).find(v=>idiomasDisponibles.includes(v))||"en";
const fuegos=["nine","maze","klotski","tictactoe","hanoi","stone","object"];
const claves=Object.fromEntries(fuegos.map(n=>[n,`stay_${n==="nine"?"nine_dots":n}_title`]));
const volver=document.getElementById("back-link"),navegacion=document.getElementById("fire-nav");
let textos={},fuegoActual="nine",entradaFuego=performance.now(),fuegoIniciado=false,quemando=false;
const seccion=n=>document.querySelector(`[data-fire="${n}"]`);
function esTactil(){return matchMedia("(hover:none), (pointer:coarse)").matches}
function estado(n,t=""){const e=document.querySelector(`[data-status="${n}"]`);if(e)e.textContent=t}
function nivel(n,v){estado(n,`${textos.stay_level||"Nivel"} ${v}`)}
function ceniza(origen){const r=origen.getBoundingClientRect(),c=document.createElement("div");c.className="embers";for(let i=0;i<36;i++){const p=document.createElement("i");p.className="ember";p.style.cssText=`--x:${r.left+Math.random()*r.width}px;--y:${r.top+r.height*(.25+Math.random()*.65)}px;--s:${1+Math.random()*4}px;--dx:${-28+Math.random()*56}px;--rise:${Math.random()*90}px;animation-delay:${Math.random()*.32}s`;c.appendChild(p)}document.body.appendChild(c);setTimeout(()=>c.remove(),2200)}
function consumir(nombre,reiniciar){if(quemando)return;quemando=true;const f=seccion(nombre);f.classList.add("is-burning");ceniza(f.querySelector(".drawing,.instrument")||f);window.observarUgju?.("fire_complete",nombre);setTimeout(()=>{reiniciar?.();f.classList.remove("is-burning");quemando=false},1900)}
function mostrarFuego(nombre){if(quemando)return;if(fuegoIniciado)window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000);fuegoActual=nombre;entradaFuego=performance.now();fuegoIniciado=true;window.observarUgju?.("fire_open",nombre);document.querySelectorAll(".fire").forEach(f=>{const a=f.dataset.fire===nombre;f.hidden=!a;f.classList.toggle("is-active",a)});navegacion.querySelectorAll("button").forEach(i=>i.setAttribute("aria-current",String(i.dataset.fire===nombre)));history.replaceState(null,"",`#${nombre}`);({nine:prepararNueve,maze:prepararLaberinto,klotski:prepararKlotski,hanoi:dibujarHanoi}[nombre]||(()=>{}))()}
function moverFuego(d){const i=fuegos.indexOf(fuegoActual),s=i+d;if(s>=0&&s<fuegos.length)mostrarFuego(fuegos[s])}
function crearNavegacion(){fuegos.forEach(n=>{const b=document.createElement("button");b.type="button";b.dataset.fire=n;b.setAttribute("aria-label",textos[claves[n]]||n);b.onclick=()=>mostrarFuego(n);navegacion.appendChild(b)})}
async function cargarTextos(){let codigo=idioma,r=await fetch(`lang/${codigo}.json?v=20260815-1`);if(!r.ok){codigo="en";r=await fetch("lang/en.json?v=20260815-1")}textos=await r.json();document.documentElement.lang=codigo;document.querySelectorAll("[data-text]").forEach(n=>n.textContent=textos[n.dataset.text]||n.textContent);document.getElementById("nine-instruction").textContent=esTactil()?textos.stay_nine_dots_instruction_touch:textos.stay_nine_dots_instruction_pointer;volver.setAttribute("aria-label",textos.stay_back_to_radio);navegacion.setAttribute("aria-label",textos.stay_fires_label||"Fuegos");crearNavegacion()}

// Nueve puntos
const lienzoNueve=document.getElementById("nine-canvas"),contenedorNueve=document.getElementById("nine-drawing"),ctxNueve=lienzoNueve.getContext("2d");let puntosTrazo=[],dibujando=false,puntosObjetivo=[];
function prepararNueve(){const r=contenedorNueve.getBoundingClientRect(),e=Math.min(devicePixelRatio||1,2);lienzoNueve.width=Math.round(r.width*e);lienzoNueve.height=Math.round(r.height*e);ctxNueve.setTransform(e,0,0,e,0,0);const m=r.width*.27,p=(r.width-m*2)/2;puntosObjetivo=[];for(let y=0;y<3;y++)for(let x=0;x<3;x++)puntosObjetivo.push({x:m+x*p,y:m+y*p});dibujarNueve()}
function dibujarNueve(){const r=contenedorNueve.getBoundingClientRect();ctxNueve.clearRect(0,0,r.width,r.height);ctxNueve.fillStyle="#222";puntosObjetivo.forEach(p=>{ctxNueve.beginPath();ctxNueve.arc(p.x,p.y,esTactil()?5.8:4.6,0,Math.PI*2);ctxNueve.fill()});if(puntosTrazo.length<2)return;ctxNueve.strokeStyle="#222";ctxNueve.lineWidth=esTactil()?11:3.2;ctxNueve.lineCap="round";ctxNueve.lineJoin="round";ctxNueve.beginPath();ctxNueve.moveTo(puntosTrazo[0].x,puntosTrazo[0].y);puntosTrazo.slice(1).forEach(p=>ctxNueve.lineTo(p.x,p.y));ctxNueve.stroke()}
function punto(e,el=lienzoNueve){const r=el.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function distanciaSegmento(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=dx||dy?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}
function simplificar(ps,t){if(ps.length<=2)return ps;let m=0,i=0;for(let n=1;n<ps.length-1;n++){const d=distanciaSegmento(ps[n],ps[0],ps.at(-1));if(d>m){m=d;i=n}}if(m<=t)return[ps[0],ps.at(-1)];return simplificar(ps.slice(0,i+1),t).slice(0,-1).concat(simplificar(ps.slice(i),t))}
function reiniciarNueve(){dibujando=false;puntosTrazo=[];dibujarNueve()}
lienzoNueve.onpointerdown=e=>{if(e.button>0||quemando)return;e.preventDefault();puntosTrazo=[punto(e)];dibujando=true;lienzoNueve.setPointerCapture(e.pointerId)};
lienzoNueve.onpointermove=e=>{if(!dibujando)return;e.preventDefault();const eventos=e.getCoalescedEvents?.()||[e];eventos.forEach(v=>puntosTrazo.push(punto(v)));dibujarNueve()};
lienzoNueve.onpointerup=e=>{if(!dibujando)return;dibujando=false;const v=simplificar(puntosTrazo,contenedorNueve.clientWidth*.025);while(v.length>5)v.splice(1,1);const ok=v.length===5&&puntosObjetivo.every(p=>v.slice(0,-1).some((a,i)=>distanciaSegmento(p,a,v[i+1])<=contenedorNueve.clientWidth*.052));puntosTrazo=v;dibujarNueve();ok?consumir("nine",reiniciarNueve):reiniciarNueve()};lienzoNueve.onpointercancel=reiniciarNueve;

// Laberinto: el aro debe permanecer sobre el hilo.
const laberinto=document.querySelector('[data-firepiece="maze"]'),svgLaberinto=laberinto.querySelector("svg"),caminoLaberinto=laberinto.querySelector(".maze-path"),aro=laberinto.querySelector(".maze-ring"),meta=laberinto.querySelector(".maze-goal");
const trazados=["M35 250 C35 180 90 210 92 145 S45 45 115 48 S142 122 188 100 S250 45 260 105 S207 163 231 207 S268 252 252 263","M35 250 C80 278 95 226 62 196 S30 126 79 132 S143 187 160 132 S105 54 167 39 S248 45 231 103 S190 171 241 179 S271 229 252 263","M35 250 C77 282 117 248 84 218 S28 190 53 151 S125 184 127 126 S70 71 125 44 S188 82 174 124 S147 197 205 169 S278 181 239 220 S232 252 252 263"];
let nivelLaberinto=0,largoLaberinto=0,arrastrandoAro=false,avanceAro=0;
function ponerAro(l){const p=caminoLaberinto.getPointAtLength(l);aro.setAttribute("cx",p.x);aro.setAttribute("cy",p.y)}
function prepararLaberinto(){caminoLaberinto.setAttribute("d",trazados[nivelLaberinto]);largoLaberinto=caminoLaberinto.getTotalLength();avanceAro=0;ponerAro(0);const p=caminoLaberinto.getPointAtLength(largoLaberinto);meta.setAttribute("cx",p.x);meta.setAttribute("cy",p.y);nivel("maze",nivelLaberinto+1)}
function localSvg(e){const p=svgLaberinto.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svgLaberinto.getScreenCTM().inverse())}
function puntoCamino(e){const p=localSvg(e);let mejor={d:Infinity,l:avanceAro};for(let l=Math.max(0,avanceAro-24);l<=Math.min(largoLaberinto,avanceAro+52);l+=2){const q=caminoLaberinto.getPointAtLength(l),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<mejor.d)mejor={d,l}}return mejor}
function falloLaberinto(){arrastrandoAro=false;laberinto.classList.remove("is-dragging");navigator.vibrate?.(35);avanceAro=Math.max(0,avanceAro-35);ponerAro(avanceAro)}
aro.onpointerdown=e=>{if(quemando)return;arrastrandoAro=true;laberinto.classList.add("is-dragging");svgLaberinto.setPointerCapture(e.pointerId);e.preventDefault()};svgLaberinto.onpointermove=e=>{if(!arrastrandoAro)return;const p=puntoCamino(e);if(p.d>18||p.l+18<avanceAro){falloLaberinto();return}avanceAro=Math.max(avanceAro,p.l);ponerAro(avanceAro);if(avanceAro>largoLaberinto-15){arrastrandoAro=false;nivelLaberinto=(nivelLaberinto+1)%trazados.length;consumir("maze",prepararLaberinto)}e.preventDefault()};svgLaberinto.onpointerup=()=>{if(arrastrandoAro)falloLaberinto()};

// Klotski: arrastrar una pieza hacia una celda libre.
const klotski=document.querySelector('[data-firepiece="klotski"]');let nivelKlotski=0,piezas=[];
const esquemas=[[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[0,2,1,2],[3,2,1,2],[1,2,2,1],[0,4,1,1],[3,4,1,1]],[[1,0,2,2,1],[0,0,1,1],[3,0,1,1],[0,1,1,2],[3,1,1,2],[1,2,1,2],[2,2,1,2],[0,3,1,1],[3,3,1,1]],[[1,0,2,2,1],[0,0,1,2],[3,0,1,2],[1,2,2,1],[0,2,1,1],[3,2,1,1],[0,3,2,1],[2,3,2,1]]];
function libre(p,nx,ny){if(nx<0||ny<0||nx+p.w>4||ny+p.h>5)return false;return !piezas.some(o=>o!==p&&nx<o.x+o.w&&nx+p.w>o.x&&ny<o.y+o.h&&ny+p.h>o.y)}
function dibujarKlotski(){klotski.replaceChildren();piezas.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.className=p.key?"is-key":"";b.style.cssText=`--x:${p.x};--y:${p.y};--w:${p.w};--h:${p.h}`;b.setAttribute("aria-label",p.key?"Pieza principal":`Pieza ${i+1}`);let sx,sy;b.onpointerdown=e=>{sx=e.clientX;sy=e.clientY;b.setPointerCapture(e.pointerId)};b.onpointerup=e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;const [mx,my]=Math.abs(dx)>Math.abs(dy)?[Math.sign(dx),0]:[0,Math.sign(dy)];if(libre(p,p.x+mx,p.y+my)){p.x+=mx;p.y+=my;dibujarKlotski();if(p.key&&p.x===1&&p.y+p.h===5){nivelKlotski=(nivelKlotski+1)%esquemas.length;consumir("klotski",prepararKlotski)}}};klotski.appendChild(b)})}
function prepararKlotski(){piezas=esquemas[nivelKlotski].map(([x,y,w,h,key])=>({x,y,w,h,key:!!key}));dibujarKlotski();nivel("klotski",nivelKlotski+1)}

// Ta-te-ti clásico: X contra O.
const tresEnRaya=document.querySelector('[data-firepiece="tictactoe"]');let tableroRaya=Array(9).fill(""),finRaya=false;const lineasRaya=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const ganador=m=>lineasRaya.some(l=>l.every(i=>tableroRaya[i]===m));
function reiniciarRaya(){tableroRaya=Array(9).fill("");finRaya=false;tresEnRaya.classList.remove("is-thinking");[...tresEnRaya.children].forEach(c=>delete c.dataset.mark);estado("tictactoe")}
function terminarRaya(){finRaya=true;consumir("tictactoe",reiniciarRaya)}
function maquina(){if(finRaya)return;const libres=tableroRaya.map((v,i)=>v?null:i).filter(i=>i!==null);let n=libres.find(i=>{tableroRaya[i]="machine";const g=ganador("machine");tableroRaya[i]="";return g});if(n===undefined)n=libres.find(i=>{tableroRaya[i]="human";const g=ganador("human");tableroRaya[i]="";return g});if(n===undefined&&libres.includes(4))n=4;if(n===undefined)n=libres[Math.floor(Math.random()*libres.length)];tableroRaya[n]="machine";tresEnRaya.children[n].dataset.mark="machine";tresEnRaya.classList.remove("is-thinking");if(ganador("machine")||tableroRaya.every(Boolean))terminarRaya()}
for(let i=0;i<9;i++){const c=document.createElement("button");c.type="button";c.setAttribute("role","gridcell");c.setAttribute("aria-label",`Casilla ${i+1}`);c.onclick=()=>{if(finRaya||tableroRaya[i]||quemando)return;tableroRaya[i]="human";c.dataset.mark="human";if(ganador("human")||tableroRaya.every(Boolean))return terminarRaya();tresEnRaya.classList.add("is-thinking");setTimeout(maquina,420)};tresEnRaya.appendChild(c)}

// Hanoi aumenta de tres a cinco discos.
const hanoi=document.querySelector('[data-firepiece="hanoi"]'),varillas=[...hanoi.querySelectorAll("button")];let nivelHanoi=0,torres=[],seleccionHanoi=null;
function reiniciarHanoi(){const n=3+nivelHanoi;torres=[Array.from({length:n},(_,i)=>n-i),[],[]];seleccionHanoi=null;dibujarHanoi();nivel("hanoi",nivelHanoi+1)}
function dibujarHanoi(){if(!torres.length)return reiniciarHanoi();varillas.forEach((v,i)=>{v.replaceChildren();delete v.dataset.selected;torres[i].forEach((d,n)=>{const e=document.createElement("i");e.style.setProperty("--w",`${25+d*11}%`);e.style.setProperty("--b",`${n*10}%`);v.appendChild(e)})})}
varillas.forEach((v,i)=>v.onclick=()=>{if(quemando)return;if(seleccionHanoi===null){if(!torres[i].length)return;seleccionHanoi=i;v.dataset.selected="true";return}const o=seleccionHanoi,d=torres[o].at(-1),tope=torres[i].at(-1);seleccionHanoi=null;dibujarHanoi();if(i===o)return;if(tope&&tope<d){navigator.vibrate?.(25);return}torres[o].pop();torres[i].push(d);dibujarHanoi();if(torres[2].length===3+nivelHanoi){nivelHanoi=(nivelHanoi+1)%3;consumir("hanoi",reiniciarHanoi)}});

// Piedra: rotar y modular sus cuatro caras.
const piedra=document.querySelector('[data-firepiece="stone"] button'),formaPiedra=piedra.querySelector("i");let girandoPiedra=false,xPiedra=0,anguloPiedra=0,caraPiedra=0,vueltasPiedra=0;
piedra.onpointerdown=e=>{girandoPiedra=true;xPiedra=e.clientX;piedra.classList.add("is-held");piedra.setPointerCapture(e.pointerId)};piedra.onpointermove=e=>{if(!girandoPiedra)return;const d=e.clientX-xPiedra;xPiedra=e.clientX;anguloPiedra+=d*.8;vueltasPiedra+=Math.abs(d);formaPiedra.style.transform=`rotate(${anguloPiedra}deg) scale(${1+Math.sin(anguloPiedra*.025)*.06})`;e.preventDefault()};piedra.onpointerup=()=>{girandoPiedra=false;piedra.classList.remove("is-held");caraPiedra=(caraPiedra+1)%4;piedra.dataset.face=caraPiedra;if(vueltasPiedra>700){vueltasPiedra=0;consumir("stone",()=>{caraPiedra=0;delete piedra.dataset.face;formaPiedra.style.transform=""})}};piedra.onpointercancel=piedra.onpointerup;

// El giro revela una puerta que estaba dentro de la forma imposible.
const campoObjeto=document.querySelector('[data-firepiece="object"]'),objeto=campoObjeto.querySelector("button"),formaObjeto=objeto.querySelector("svg");let girandoObjeto=false,ultimoX=0,anguloObjeto=0,recorridoObjeto=0;
objeto.onpointerdown=e=>{girandoObjeto=true;ultimoX=e.clientX;objeto.setPointerCapture(e.pointerId);e.preventDefault()};objeto.onpointermove=e=>{if(!girandoObjeto)return;const d=e.clientX-ultimoX;ultimoX=e.clientX;anguloObjeto+=d*.75;recorridoObjeto+=Math.abs(d);formaObjeto.style.transform=`rotate(${anguloObjeto}deg) skewY(${Math.sin(anguloObjeto*Math.PI/180)*9}deg)`;if(recorridoObjeto>360)campoObjeto.classList.add("is-revealed");if(recorridoObjeto>560){girandoObjeto=false;consumir("object",()=>{recorridoObjeto=0;anguloObjeto=0;campoObjeto.classList.remove("is-revealed");formaObjeto.style.transform=""})}e.preventDefault()};objeto.onpointerup=objeto.onpointercancel=()=>{girandoObjeto=false};

let inicioSwipe=null;function interactivo(e){return e.closest("[data-firepiece],canvas,button,a")};document.addEventListener("touchstart",e=>{if(e.touches.length!==1||interactivo(e.target))return;const t=e.touches[0];inicioSwipe={x:t.clientX,y:t.clientY}},{passive:true});document.addEventListener("touchend",e=>{if(!inicioSwipe)return;const t=e.changedTouches[0],dx=t.clientX-inicioSwipe.x,dy=t.clientY-inicioSwipe.y;inicioSwipe=null;if(Math.abs(dx)>96&&Math.abs(dx)>Math.abs(dy)*1.4)moverFuego(dx<0?1:-1)},{passive:true});
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight")moverFuego(1);if(e.key==="ArrowLeft")moverFuego(-1)});window.addEventListener("pagehide",()=>window.observarUgju?.("fire_dwell",fuegoActual,(performance.now()-entradaFuego)/1000));volver.onclick=e=>{if(parent===window)return;e.preventDefault();parent.postMessage({type:"close-stay"},location.origin)};window.addEventListener("resize",()=>{if(fuegoActual==="nine")prepararNueve()});
cargarTextos().catch(()=>{}).finally(()=>{prepararKlotski();reiniciarHanoi();mostrarFuego(fuegos.includes(location.hash.slice(1))?location.hash.slice(1):"nine")});
